package golang

import (
	"bytes"
	"regexp"
	"strings"
	"testing"

	"github.com/arsfy/gcorm/pkg/schema/ir"
)

// goldenSchema returns a fixed schema used for golden output tests.
func goldenSchema() *ir.Schema {
	return &ir.Schema{
		Datasource: &ir.Datasource{Provider: "postgresql"},
		Generators: []*ir.Generator{{Name: "client", Provider: "gco-go", Output: "./gen", Package: "db"}},
		Models: []*ir.Model{
			{
				Name: "User",
				Fields: []*ir.Field{
					{Name: "id", Type: ir.FieldKindScalar, ScalarType: "String", IsID: true},
					{Name: "email", Type: ir.FieldKindScalar, ScalarType: "String", IsUnique: true},
					{Name: "name", Type: ir.FieldKindScalar, ScalarType: "String", IsOptional: true},
					{Name: "createdAt", Type: ir.FieldKindScalar, ScalarType: "DateTime"},
				},
				PrimaryKey: &ir.PrimaryKey{Fields: []string{"id"}},
			},
			{
				Name: "Post",
				Fields: []*ir.Field{
					{Name: "id", Type: ir.FieldKindScalar, ScalarType: "String", IsID: true},
					{Name: "title", Type: ir.FieldKindScalar, ScalarType: "String"},
					{Name: "published", Type: ir.FieldKindScalar, ScalarType: "Boolean"},
					{Name: "authorId", Type: ir.FieldKindScalar, ScalarType: "String"},
					{Name: "author", Type: ir.FieldKindRelation, ModelType: "User"},
				},
				PrimaryKey: &ir.PrimaryKey{Fields: []string{"id"}},
			},
		},
		Enums: []*ir.Enum{
			{Name: "Role", Values: []*ir.EnumValue{{Name: "USER"}, {Name: "ADMIN"}}},
		},
	}
}

// generateGoldenFiles is a helper that generates all files from the golden schema.
func generateGoldenFiles(t *testing.T) []*GeneratedFile {
	t.Helper()
	g := NewGenerator(goldenSchema())
	files, err := g.Generate()
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}
	return files
}

// fileContent returns the string content of the generated file at the given path.
func fileContent(t *testing.T, files []*GeneratedFile, path string) string {
	t.Helper()
	for _, f := range files {
		if f.Path == path {
			return string(f.Content)
		}
	}
	t.Fatalf("file %q not found in generated output", path)
	return ""
}

func TestGoldenModelOutput(t *testing.T) {
	files := generateGoldenFiles(t)
	content := fileContent(t, files, "model/models.go")

	checks := []string{
		"// Code generated by GCORM. DO NOT EDIT.",
		"package model",
		"type User struct {",
		"type Post struct {",
	}
	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Errorf("model/models.go missing %q", check)
		}
	}

	// Verify User fields are present with db/json tags.
	if !strings.Contains(content, `db:"id"`) {
		t.Error("model/models.go missing db:\"id\" tag")
	}
	if !strings.Contains(content, `json:"email"`) {
		t.Error("model/models.go missing json:\"email\" tag")
	}
}

func TestGoldenEnumOutput(t *testing.T) {
	files := generateGoldenFiles(t)
	content := fileContent(t, files, "model/enums.go")

	checks := []string{
		"type Role string",
		`RoleUSER`,
		`RoleADMIN`,
		"func ValidRoleValues() []Role",
	}
	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Errorf("model/enums.go missing %q", check)
		}
	}

	// Ensure the constant values are correct (gofmt may align with extra spaces).
	if !strings.Contains(content, `RoleUSER`) || !strings.Contains(content, `Role = "USER"`) {
		t.Error("model/enums.go missing RoleUSER constant definition")
	}
	if !strings.Contains(content, `RoleADMIN`) || !strings.Contains(content, `Role = "ADMIN"`) {
		t.Error("model/enums.go missing RoleADMIN constant definition")
	}
}

func TestGoldenClientOutput(t *testing.T) {
	files := generateGoldenFiles(t)
	content := fileContent(t, files, "client/client.go")

	checks := []string{
		"func New(db *sql.DB, opts ...Option) *Client",
		"func (c *Client) Tx(ctx context.Context",
		"type PostActions struct",
		"type UserCreateBuilder struct",
		"type UserCreateManyBuilder struct",
		"type UserQueryBuilder struct",
		"type UserUpdateBuilder struct",
		"type UserDeleteBuilder struct",
		"func (a UserActions) Create() UserCreateBuilder",
		"func (a UserActions) BulkCreate(data []query.UserCreateInput) UserCreateManyBuilder",
		"func (a UserActions) Query() UserQueryBuilder",
		"func (a UserActions) Update() UserUpdateBuilder",
		"func (a UserActions) Delete() UserDeleteBuilder",
		"func (b UserCreateBuilder) Do(ctx context.Context) (*model.User, error)",
		"func (b UserCreateManyBuilder) OnConflictDoNothing(columns ...string) UserCreateManyBuilder",
		"func (b UserCreateManyBuilder) Returning(columns ...string) UserCreateManyBuilder",
		"func (b UserCreateManyBuilder) BatchSize(n int) UserCreateManyBuilder",
		"func (b UserCreateManyBuilder) DoReturning(ctx context.Context) ([]model.User, error)",
		"func (b UserCreateManyBuilder) DoReturningValues(ctx context.Context) ([]map[string]any, error)",
		"func (b UserQueryBuilder) Do(ctx context.Context) ([]model.User, error)",
		"func (b UserQueryBuilder) First(ctx context.Context) (*model.User, error)",
		"func (b UserQueryBuilder) Count(ctx context.Context) (int64, error)",
		"func (b UserUpdateBuilder) Do(ctx context.Context) (*model.User, error)",
		"func (b UserUpdateBuilder) DoMany(ctx context.Context) (int64, error)",
		"func (b UserDeleteBuilder) Do(ctx context.Context) (*model.User, error)",
		"func (b UserDeleteBuilder) DoMany(ctx context.Context) (int64, error)",
		"type UserActions struct",
		"FindMany",
		"CreateOne",
		"DeleteOne",
		"Count",
		"Aggregate",
		"GroupBy",
		"WithDialect",
		"placeholder",
	}
	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Errorf("client/client.go missing %q", check)
		}
	}
}

func TestGoldenQueryOutput(t *testing.T) {
	files := generateGoldenFiles(t)

	// Check User query file.
	userQuery := fileContent(t, files, "query/user.go")
	userChecks := []string{
		"Equals(",
		"Not(",
		"In(",
		"Contains(", // String fields should have Contains
		"Set(",      // create/update set
		"Asc()",
		"Desc()",
	}
	for _, check := range userChecks {
		if !strings.Contains(userQuery, check) {
			t.Errorf("query/user.go missing %q", check)
		}
	}
	// DateTime field (createdAt) should have Lt/Gt.
	if !strings.Contains(userQuery, "Lt(") {
		t.Error("query/user.go missing Lt( for DateTime field")
	}
	if !strings.Contains(userQuery, "Gt(") {
		t.Error("query/user.go missing Gt( for DateTime field")
	}

	// New features: QueryOption, AND/OR/NOT, Cursor, Aggregate/GroupBy, CreateInput.
	newQueryChecks := []string{
		"UserQueryOption",
		"UserQueryConfig",
		"var User = UserQuery{",
		"ApplyUserOptions",
		"UserTakeOption",
		"UserSkipOption",
		"func (UserQuery) AND(",
		"func (UserQuery) OR(",
		"func (UserQuery) NOT(",
		"func (UserQuery) Cursor(",
		"UserAggregateOption",
		"UserAggregateResult",
		"UserGroupByResult",
		"UserCreateInput",
		"UserCreateNestedInput",
		"UserWhereUniqueInput",
		"ScalarValues()",
		`const UserTable = "User"`,
		`const UserCreatedAtColumn = "created_at"`,
	}
	for _, check := range newQueryChecks {
		if !strings.Contains(userQuery, check) {
			t.Errorf("query/user.go missing %q", check)
		}
	}
	if !regexp.MustCompile(`(?m)\bEmail\s+userEmailField\b`).MatchString(userQuery) {
		t.Error("query/user.go should scope Email under UserQuery")
	}
	if !regexp.MustCompile(`(?m)\bCreatedAt\s+userCreatedAtField\b`).MatchString(userQuery) {
		t.Error("query/user.go should scope CreatedAt under UserQuery")
	}
	if !strings.Contains(userQuery, "func (userNameField) Set(v string) UserSetClause") {
		t.Error("query/user.go should allow plain values in Set for optional string fields")
	}
	if !strings.Contains(userQuery, "func (userNameField) SetNull() UserSetClause") {
		t.Error("query/user.go should generate SetNull for optional string fields")
	}
	if strings.Contains(userQuery, "var UserEmail =") {
		t.Error("query/user.go should not generate flattened UserEmail helper vars")
	}

	// In method should convert to []any for type-safe SQL building.
	if !strings.Contains(userQuery, "iVals := make([]any, len(vals))") {
		t.Error("query/user.go In() should convert to []any")
	}

	// Check Post query file.
	postQuery := fileContent(t, files, "query/post.go")
	postChecks := []string{
		"Equals(",
		"Not(",
		"In(",
		"Set(",
		"Asc()",
		"Desc()",
		"var Post = PostQuery{",
		"PostQueryOption",
		"PostCreateInput",
	}
	for _, check := range postChecks {
		if !strings.Contains(postQuery, check) {
			t.Errorf("query/post.go missing %q", check)
		}
	}
	if !regexp.MustCompile(`(?m)\bAuthor\s+postAuthorRelation\b`).MatchString(postQuery) {
		t.Error("query/post.go should scope Author under PostQuery")
	}
}

func TestGoldenColumnNamesUseResolvedDBName(t *testing.T) {
	schema := &ir.Schema{
		Datasource: &ir.Datasource{Provider: "postgresql"},
		Generators: []*ir.Generator{{Name: "go", Package: "db", Output: "./gen"}},
		Models: []*ir.Model{
			{
				Name: "Thing",
				Fields: []*ir.Field{
					{Name: "id", Type: ir.FieldKindScalar, ScalarType: "String", IsID: true},
					{Name: "abcAbc", Type: ir.FieldKindScalar, ScalarType: "String"},
					{Name: "mappedField", DBName: "custom_column", Type: ir.FieldKindScalar, ScalarType: "String"},
				},
				PrimaryKey: &ir.PrimaryKey{Fields: []string{"id"}},
			},
		},
	}
	g := NewGenerator(schema)
	files, err := g.Generate()
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}

	models := fileContent(t, files, "model/models.go")
	if !strings.Contains(models, `db:"abc_abc"`) {
		t.Fatalf("model should use snake_case db tag for abcAbc:\n%s", models)
	}
	if !strings.Contains(models, `db:"custom_column"`) {
		t.Fatalf("model should respect explicit DBName:\n%s", models)
	}

	query := fileContent(t, files, "query/thing.go")
	if !strings.Contains(query, `Field: "abc_abc"`) {
		t.Fatalf("query should use snake_case column for abcAbc:\n%s", query)
	}
	if !strings.Contains(query, `Field: "custom_column"`) {
		t.Fatalf("query should respect explicit DBName:\n%s", query)
	}
	if strings.Contains(query, `Field: "abcAbc"`) {
		t.Fatalf("query should not use raw camelCase field name:\n%s", query)
	}
}

func TestGoldenClientRealMethods(t *testing.T) {
	files := generateGoldenFiles(t)
	content := fileContent(t, files, "client/client.go")

	// Verify real SQL execution code is generated (not stubs).
	realCodeChecks := []string{
		"QueryContext(ctx,",
		"ExecContext(ctx,",
		"QueryRowContext(ctx,",
		"rows.Scan(",
		"row.Scan(",
		"rows.Close()",
		"rows.Next()",
		"rows.Err()",
		"sql.ErrNoRows",
		"buildUserWhere(",
		"buildPostWhere(",
		"SELECT",
		"INSERT INTO",
		"UPDATE",
		"DELETE FROM",
		"RETURNING",
		"WHERE",
		"ORDER BY",
		"LIMIT",
		"OFFSET",
		"ON CONFLICT",
		"COUNT(*)",
		"NullFloat64",
		"GROUP BY",
	}
	for _, check := range realCodeChecks {
		if !strings.Contains(content, check) {
			t.Errorf("client/client.go missing real SQL code %q", check)
		}
	}

	// Verify all 13 methods are present for each model.
	methods := []string{
		"FindMany", "FindFirst", "FindUnique",
		"Create", "BulkCreate", "Query", "Update", "Delete",
		"CreateOne", "CreateMany",
		"UpdateOne", "UpdateMany",
		"UpsertOne",
		"DeleteOne", "DeleteMany",
		"Count", "Aggregate", "GroupBy",
	}
	for _, m := range methods {
		if !strings.Contains(content, "func (a UserActions) "+m+"(") {
			t.Errorf("client/client.go missing User method %s", m)
		}
		if !strings.Contains(content, "func (a PostActions) "+m+"(") {
			t.Errorf("client/client.go missing Post method %s", m)
		}
	}

	// Verify placeholder helper handles both dialects.
	if !strings.Contains(content, `dialect == "postgresql"`) {
		t.Error("client/client.go should handle postgresql dialect")
	}
}

func TestGoldenClientTableNames(t *testing.T) {
	// Test with a model that has DBName set.
	schema := &ir.Schema{
		Datasource: &ir.Datasource{Provider: "postgresql"},
		Generators: []*ir.Generator{{Name: "go", Package: "db", Output: "./gen"}},
		Models: []*ir.Model{
			{
				Name:   "User",
				DBName: "app_users",
				Fields: []*ir.Field{
					{Name: "id", Type: ir.FieldKindScalar, ScalarType: "String", IsID: true},
				},
				PrimaryKey: &ir.PrimaryKey{Fields: []string{"id"}},
			},
		},
	}
	g := NewGenerator(schema)
	files, err := g.Generate()
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}
	content := fileContent(t, files, "client/client.go")
	if !strings.Contains(content, "app_users") {
		t.Error("client should use DBName 'app_users' as table name")
	}
}

func TestGoldenDeterminism(t *testing.T) {
	schema := goldenSchema()

	g1 := NewGenerator(schema)
	files1, err := g1.Generate()
	if err != nil {
		t.Fatalf("first Generate() error: %v", err)
	}

	g2 := NewGenerator(schema)
	files2, err := g2.Generate()
	if err != nil {
		t.Fatalf("second Generate() error: %v", err)
	}

	if len(files1) != len(files2) {
		t.Fatalf("file counts differ: %d vs %d", len(files1), len(files2))
	}

	for i := range files1 {
		if files1[i].Path != files2[i].Path {
			t.Errorf("path[%d]: %q vs %q", i, files1[i].Path, files2[i].Path)
		}
		if !bytes.Equal(files1[i].Content, files2[i].Content) {
			t.Errorf("content differs for %s", files1[i].Path)
		}
	}
}

func TestGoldenDoNotEditHeader(t *testing.T) {
	files := generateGoldenFiles(t)
	header := "// Code generated by GCORM. DO NOT EDIT."

	for _, f := range files {
		content := string(f.Content)
		if !strings.HasPrefix(content, header) {
			t.Errorf("file %s does not start with DO NOT EDIT header;\nstarts with: %q",
				f.Path, content[:min(len(content), 60)])
		}
	}
}
