package golang

// Template for enum types.
var enumsTmpl = `// Code generated by GCO ORM. DO NOT EDIT.
package model

{{range .Enums}}
// {{.Name}} represents the {{.Name}} enum type.
type {{.Name}} string

const (
{{- range .Values}}
	{{$.Enums}}{{.Name}} {{$.Enums}}{{$.Enums}} = "{{.Name}}"
{{- end}}
)
{{end}}
`

func init() {
	// Fix the enums template to use proper enum references.
	enumsTmpl = `// Code generated by GCO ORM. DO NOT EDIT.
package model

{{range $enum := .Enums}}
// {{$enum.Name}} represents the {{$enum.Name}} enum type.
type {{$enum.Name}} string

const (
{{- range $val := $enum.Values}}
	{{$enum.Name}}{{$val.Name}} {{$enum.Name}} = "{{$val.Name}}"
{{- end}}
)

// Valid{{$enum.Name}}Values returns all valid values for the {{$enum.Name}} enum.
func Valid{{$enum.Name}}Values() []{{$enum.Name}} {
	return []{{$enum.Name}}{
{{- range $val := $enum.Values}}
		{{$enum.Name}}{{$val.Name}},
{{- end}}
	}
}
{{end}}
`
}

// Template for model struct types.
var modelsTmpl = `// Code generated by GCO ORM. DO NOT EDIT.
package model

{{- $needsTime := false}}
{{- $needsJSON := false}}
{{- range .Models}}
{{- range .Fields}}
{{- if and (eq .Type 0) (eq .ScalarType "DateTime")}}{{$needsTime = true}}{{end}}
{{- if and (eq .Type 0) (eq .ScalarType "Json")}}{{$needsJSON = true}}{{end}}
{{- end}}
{{- end}}

{{if or $needsTime $needsJSON}}
import (
{{- if $needsTime}}
	"time"
{{- end}}
{{- if $needsJSON}}
	"encoding/json"
{{- end}}
)
{{end}}

{{range $model := .Models}}
// {{$model.Name}} represents the {{$model.Name}} model.
type {{$model.Name}} struct {
{{- range $field := $model.Fields}}
{{- if ne $field.Type 2}}
	{{upper $field.Name}} {{goType $field}} ` + "`" + `db:"{{snakeCase $field.Name}}" json:"{{lower $field.Name}}"` + "`" + `
{{- end}}
{{- end}}
{{- range $field := $model.Fields}}
{{- if eq $field.Type 2}}
	{{upper $field.Name}} {{goType $field}} ` + "`" + `db:"-" json:"{{lower $field.Name}},omitempty"` + "`" + `
{{- end}}
{{- end}}
}
{{end}}
`

// Template for query builder per model.
var queryTmpl = `// Code generated by GCO ORM. DO NOT EDIT.
package query

{{- $needsTime := false}}
{{- $needsJSON := false}}
{{- range .Model.Fields}}
{{- if and (eq .Type 0) (eq .ScalarType "DateTime")}}{{$needsTime = true}}{{end}}
{{- if and (eq .Type 0) (eq .ScalarType "Json")}}{{$needsJSON = true}}{{end}}
{{- end}}

{{if or $needsTime $needsJSON}}
import (
{{- if $needsTime}}
	"time"
{{- end}}
{{- if $needsJSON}}
	"encoding/json"
{{- end}}
)
{{end}}

// {{.Model.Name}}QueryOption configures a {{.Model.Name}} query.
type {{.Model.Name}}QueryOption interface {
	apply{{.Model.Name}}Query(*{{.Model.Name}}QueryConfig)
}

// {{.Model.Name}}QueryConfig collects query parameters for {{.Model.Name}}.
type {{.Model.Name}}QueryConfig struct {
	Wheres   []{{.Model.Name}}WhereClause
	OrderBys []{{.Model.Name}}OrderByClause
	Includes []{{.Model.Name}}IncludeClause
	Take     *int
	Skip     *int
}

// Apply{{.Model.Name}}Options applies a list of query options to produce a QueryConfig.
func Apply{{.Model.Name}}Options(opts []{{.Model.Name}}QueryOption) {{.Model.Name}}QueryConfig {
	var cfg {{.Model.Name}}QueryConfig
	for _, opt := range opts {
		opt.apply{{.Model.Name}}Query(&cfg)
	}
	return cfg
}

// {{.Model.Name}}Query provides query building methods for the {{.Model.Name}} model.
var {{.Model.Name}} = {{.Model.Name}}Query{}

// {{.Model.Name}}Query is the namespace for {{.Model.Name}} query operations.
type {{.Model.Name}}Query struct{}

// {{.Model.Name}}WhereClause represents a WHERE condition for {{.Model.Name}}.
type {{.Model.Name}}WhereClause struct {
	Field    string
	Operator string
	Value    any
}

func (w {{.Model.Name}}WhereClause) apply{{.Model.Name}}Query(c *{{.Model.Name}}QueryConfig) {
	c.Wheres = append(c.Wheres, w)
}

// {{.Model.Name}}OrderByClause represents an ORDER BY clause for {{.Model.Name}}.
type {{.Model.Name}}OrderByClause struct {
	Field     string
	Direction string // "ASC" or "DESC"
}

func (o {{.Model.Name}}OrderByClause) apply{{.Model.Name}}Query(c *{{.Model.Name}}QueryConfig) {
	c.OrderBys = append(c.OrderBys, o)
}

// {{.Model.Name}}IncludeClause represents an include directive for {{.Model.Name}}.
type {{.Model.Name}}IncludeClause struct {
	Relation string
}

func (i {{.Model.Name}}IncludeClause) apply{{.Model.Name}}Query(c *{{.Model.Name}}QueryConfig) {
	c.Includes = append(c.Includes, i)
}

// {{.Model.Name}}TakeOption limits the number of results.
type {{.Model.Name}}TakeOption struct{ N int }

func (t {{.Model.Name}}TakeOption) apply{{.Model.Name}}Query(c *{{.Model.Name}}QueryConfig) {
	c.Take = &t.N
}

// {{.Model.Name}}SkipOption skips a number of results.
type {{.Model.Name}}SkipOption struct{ N int }

func (s {{.Model.Name}}SkipOption) apply{{.Model.Name}}Query(c *{{.Model.Name}}QueryConfig) {
	c.Skip = &s.N
}

// Where creates a composite WHERE condition from multiple clauses.
func ({{.Model.Name}}Query) Where(clauses ...{{.Model.Name}}WhereClause) []{{.Model.Name}}WhereClause {
	return clauses
}

// OrderBy creates an ORDER BY clause.
func ({{.Model.Name}}Query) OrderBy(clause {{.Model.Name}}OrderByClause) {{.Model.Name}}OrderByClause {
	return clause
}

// Include creates an include directive.
func ({{.Model.Name}}Query) Include(clauses ...{{.Model.Name}}IncludeClause) []{{.Model.Name}}IncludeClause {
	return clauses
}

// Take returns a take (limit) option.
func ({{.Model.Name}}Query) Take(n int) {{.Model.Name}}TakeOption {
	return {{.Model.Name}}TakeOption{N: n}
}

// Skip returns a skip (offset) option.
func ({{.Model.Name}}Query) Skip(n int) {{.Model.Name}}SkipOption {
	return {{.Model.Name}}SkipOption{N: n}
}

// AND combines multiple WHERE clauses with AND logic.
func ({{.Model.Name}}Query) AND(clauses ...{{.Model.Name}}WhereClause) {{.Model.Name}}WhereClause {
	return {{.Model.Name}}WhereClause{Field: "__AND__", Value: clauses}
}

// OR combines multiple WHERE clauses with OR logic.
func ({{.Model.Name}}Query) OR(clauses ...{{.Model.Name}}WhereClause) {{.Model.Name}}WhereClause {
	return {{.Model.Name}}WhereClause{Field: "__OR__", Value: clauses}
}

// NOT negates a WHERE clause.
func ({{.Model.Name}}Query) NOT(clause {{.Model.Name}}WhereClause) {{.Model.Name}}WhereClause {
	return {{.Model.Name}}WhereClause{Field: "__NOT__", Value: clause}
}

// Cursor creates a cursor-based pagination condition.
func ({{.Model.Name}}Query) Cursor(field string, value any) {{.Model.Name}}WhereClause {
	return {{.Model.Name}}WhereClause{Field: field, Operator: ">", Value: value}
}

{{range $field := .Model.Fields}}
{{- if ne $field.Type 2}}
// {{upper $field.Name}}Field provides query operations for the {{$field.Name}} field.
var {{$.Model.Name}}{{upper $field.Name}} = {{lower $.Model.Name}}{{upper $field.Name}}Field{}

type {{lower $.Model.Name}}{{upper $field.Name}}Field struct{}

// Equals creates an equality condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Equals(v {{goType $field}}) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{snakeCase $field.Name}}", Operator: "=", Value: v}
}

// Not creates a not-equal condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Not(v {{goType $field}}) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{snakeCase $field.Name}}", Operator: "!=", Value: v}
}

// In creates an IN condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) In(vals ...{{goType $field}}) {{$.Model.Name}}WhereClause {
	iVals := make([]any, len(vals))
	for i, v := range vals {
		iVals[i] = v
	}
	return {{$.Model.Name}}WhereClause{Field: "{{snakeCase $field.Name}}", Operator: "IN", Value: iVals}
}

// NotIn creates a NOT IN condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) NotIn(vals ...{{goType $field}}) {{$.Model.Name}}WhereClause {
	iVals := make([]any, len(vals))
	for i, v := range vals {
		iVals[i] = v
	}
	return {{$.Model.Name}}WhereClause{Field: "{{snakeCase $field.Name}}", Operator: "NOT IN", Value: iVals}
}

{{- if or (eq $field.ScalarType "Int") (eq $field.ScalarType "BigInt") (eq $field.ScalarType "Float") (eq $field.ScalarType "Decimal") (eq $field.ScalarType "DateTime")}}

// Lt creates a less-than condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Lt(v {{goType $field}}) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{snakeCase $field.Name}}", Operator: "<", Value: v}
}

// Lte creates a less-than-or-equal condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Lte(v {{goType $field}}) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{snakeCase $field.Name}}", Operator: "<=", Value: v}
}

// Gt creates a greater-than condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Gt(v {{goType $field}}) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{snakeCase $field.Name}}", Operator: ">", Value: v}
}

// Gte creates a greater-than-or-equal condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Gte(v {{goType $field}}) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{snakeCase $field.Name}}", Operator: ">=", Value: v}
}
{{end}}

{{- if eq $field.ScalarType "String"}}

// Contains creates a LIKE '%v%' condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Contains(v string) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{snakeCase $field.Name}}", Operator: "CONTAINS", Value: v}
}

// StartsWith creates a LIKE 'v%' condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) StartsWith(v string) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{snakeCase $field.Name}}", Operator: "STARTS_WITH", Value: v}
}

// EndsWith creates a LIKE '%v' condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) EndsWith(v string) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{snakeCase $field.Name}}", Operator: "ENDS_WITH", Value: v}
}
{{end}}

{{- if $field.IsOptional}}

// IsNull creates an IS NULL condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) IsNull() {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{snakeCase $field.Name}}", Operator: "IS NULL", Value: nil}
}
{{end}}

// Set creates a set operation for create/update.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Set(v {{goType $field}}) {{$.Model.Name}}SetClause {
	return {{$.Model.Name}}SetClause{Field: "{{snakeCase $field.Name}}", Value: v}
}

// Asc returns an ascending order clause for this field.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Asc() {{$.Model.Name}}OrderByClause {
	return {{$.Model.Name}}OrderByClause{Field: "{{snakeCase $field.Name}}", Direction: "ASC"}
}

// Desc returns a descending order clause for this field.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Desc() {{$.Model.Name}}OrderByClause {
	return {{$.Model.Name}}OrderByClause{Field: "{{snakeCase $field.Name}}", Direction: "DESC"}
}
{{end}}
{{- if eq $field.Type 2}}
// {{upper $field.Name}}Relation provides relation query helpers for {{$field.Name}}.
var {{$.Model.Name}}{{upper $field.Name}} = {{lower $.Model.Name}}{{upper $field.Name}}Relation{}

type {{lower $.Model.Name}}{{upper $field.Name}}Relation struct{}

// Fetch creates an include clause to fetch related {{$field.Name}}.
func ({{lower $.Model.Name}}{{upper $field.Name}}Relation) Fetch() {{$.Model.Name}}IncludeClause {
	return {{$.Model.Name}}IncludeClause{Relation: "{{$field.Name}}"}
}
{{end}}
{{end}}

// {{.Model.Name}}SetClause represents a field set operation for create/update.
type {{.Model.Name}}SetClause struct {
	Field string
	Value any
}

// {{.Model.Name}}AggregateOption specifies an aggregate function to compute.
type {{.Model.Name}}AggregateOption struct {
	Fn    string
	Field string
}

// {{.Model.Name}}AggregateResult holds the result of an aggregate query.
type {{.Model.Name}}AggregateResult struct {
	Count int64
	Avg   map[string]*float64
	Sum   map[string]*float64
	Min   map[string]any
	Max   map[string]any
}

// {{.Model.Name}}GroupByResult holds a single row from a GROUP BY query.
type {{.Model.Name}}GroupByResult struct {
	Group map[string]any
	Count int64
	Avg   map[string]*float64
	Sum   map[string]*float64
	Min   map[string]any
	Max   map[string]any
}

// {{.Model.Name}}CreateInput holds data for creating a {{.Model.Name}} record.
type {{.Model.Name}}CreateInput struct {
{{- range scalarCols .Model}}
	{{upper .Name}} {{if .IsOptional}}*{{end}}{{goType .}}
{{- end}}
{{- range .Model.Fields}}
{{- if eq .Type 2}}
	{{upper .Name}} *{{.ModelType}}CreateNestedInput
{{- end}}
{{- end}}
}

// ScalarValues returns the scalar field values in column order.
func (d {{.Model.Name}}CreateInput) ScalarValues() []any {
	return []any{ {{createInputValues .Model}} }
}

// {{.Model.Name}}CreateNestedInput supports nested creates and connects.
type {{.Model.Name}}CreateNestedInput struct {
	Create  *{{.Model.Name}}CreateInput
	Connect *{{.Model.Name}}WhereUniqueInput
}

// {{.Model.Name}}WhereUniqueInput identifies a unique {{.Model.Name}} record.
type {{.Model.Name}}WhereUniqueInput struct {
{{- range scalarCols .Model}}
{{- if or .IsID .IsUnique}}
	{{upper .Name}} *{{goType .}}
{{- end}}
{{- end}}
}
`

// Template for the client entry point.
var clientTmpl = `// Code generated by GCO ORM. DO NOT EDIT.
package client

import (
	"context"
	"database/sql"
{{- if .Models}}
	"fmt"
	"strings"

	"{{.BaseImport}}/model"
	"{{.BaseImport}}/query"
{{- end}}
)

{{- if .Models}}

// querier is the common interface for *sql.DB and *sql.Tx.
type querier interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row
}
{{- end}}

// Client is the main entry point for database operations.
type Client struct {
	db *sql.DB
{{- if .Models}}
	executor querier
	dialect  string
{{- end}}
{{- range .Models}}
	{{.Name}} {{.Name}}Actions
{{- end}}
}

// New creates a new Client from a database connection.
func New(db *sql.DB{{if .Models}}, opts ...Option{{end}}) *Client {
	c := &Client{db: db{{if .Models}}, executor: db, dialect: "postgresql"{{end}}}
{{- if .Models}}
	for _, opt := range opts {
		opt(c)
	}
{{- end}}
{{- range .Models}}
	c.{{.Name}} = {{.Name}}Actions{client: c}
{{- end}}
	return c
}

{{- if .Models}}

// Option configures the Client.
type Option func(*Client)

// WithDialect sets the SQL dialect ("postgresql", "mysql", "sqlite").
func WithDialect(d string) Option {
	return func(c *Client) { c.dialect = d }
}
{{- end}}

// Close closes the underlying database connection.
func (c *Client) Close() error {
	return c.db.Close()
}

// DB returns the underlying *sql.DB.
func (c *Client) DB() *sql.DB {
	return c.db
}

{{- if .Models}}

// placeholder returns the parameter placeholder for the nth parameter (1-based).
func (c *Client) placeholder(n int) string {
	if c.dialect == "postgresql" {
		return fmt.Sprintf("$%d", n)
	}
	return "?"
}
{{- end}}

// Tx executes a function within a database transaction.
// If the function returns nil, the transaction is committed.
// If the function returns an error, the transaction is rolled back.
func (c *Client) Tx(ctx context.Context, fn func(tx *Client) error) error {
	sqlTx, err := c.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}

	txClient := &Client{db: c.db{{if .Models}}, executor: sqlTx, dialect: c.dialect{{end}}}
{{- range .Models}}
	txClient.{{.Name}} = {{.Name}}Actions{client: txClient}
{{- end}}

	defer func() {
		if p := recover(); p != nil {
			_ = sqlTx.Rollback()
			panic(p)
		}
	}()

	if err := fn(txClient); err != nil {
		_ = sqlTx.Rollback()
		return err
	}
	return sqlTx.Commit()
}

{{range $model := .Models}}
// build{{$model.Name}}Where recursively builds a WHERE clause string and arguments.
func build{{$model.Name}}Where(c *Client, wheres []query.{{$model.Name}}WhereClause, argIdx *int) (string, []any) {
	var parts []string
	var args []any
	for _, w := range wheres {
		switch w.Field {
		case "__AND__":
			if subs, ok := w.Value.([]query.{{$model.Name}}WhereClause); ok {
				sub, subArgs := build{{$model.Name}}Where(c, subs, argIdx)
				if sub != "" {
					parts = append(parts, "("+sub+")")
				}
				args = append(args, subArgs...)
			}
		case "__OR__":
			if subs, ok := w.Value.([]query.{{$model.Name}}WhereClause); ok {
				var orParts []string
				for _, sc := range subs {
					sub, subArgs := build{{$model.Name}}Where(c, []query.{{$model.Name}}WhereClause{sc}, argIdx)
					if sub != "" {
						orParts = append(orParts, sub)
					}
					args = append(args, subArgs...)
				}
				if len(orParts) > 0 {
					parts = append(parts, "("+strings.Join(orParts, " OR ")+")")
				}
			}
		case "__NOT__":
			if sc, ok := w.Value.(query.{{$model.Name}}WhereClause); ok {
				sub, subArgs := build{{$model.Name}}Where(c, []query.{{$model.Name}}WhereClause{sc}, argIdx)
				if sub != "" {
					parts = append(parts, "NOT ("+sub+")")
				}
				args = append(args, subArgs...)
			}
		default:
			switch w.Operator {
			case "IS NULL":
				parts = append(parts, w.Field+" IS NULL")
			case "IN", "NOT IN":
				if vals, ok := w.Value.([]any); ok {
					if len(vals) == 0 {
						if w.Operator == "IN" {
							parts = append(parts, "1 = 0")
						} else {
							parts = append(parts, "1 = 1")
						}
					} else {
						phs := make([]string, len(vals))
						for i, v := range vals {
							*argIdx++
							phs[i] = c.placeholder(*argIdx)
							args = append(args, v)
						}
						parts = append(parts, w.Field+" "+w.Operator+" ("+strings.Join(phs, ", ")+")")
					}
				}
			case "CONTAINS":
				*argIdx++
				parts = append(parts, w.Field+" LIKE "+c.placeholder(*argIdx))
				args = append(args, "%"+fmt.Sprint(w.Value)+"%")
			case "STARTS_WITH":
				*argIdx++
				parts = append(parts, w.Field+" LIKE "+c.placeholder(*argIdx))
				args = append(args, fmt.Sprint(w.Value)+"%")
			case "ENDS_WITH":
				*argIdx++
				parts = append(parts, w.Field+" LIKE "+c.placeholder(*argIdx))
				args = append(args, "%"+fmt.Sprint(w.Value))
			default:
				*argIdx++
				parts = append(parts, w.Field+" "+w.Operator+" "+c.placeholder(*argIdx))
				args = append(args, w.Value)
			}
		}
	}
	return strings.Join(parts, " AND "), args
}

// {{$model.Name}}Actions provides database operations for the {{$model.Name}} model.
type {{$model.Name}}Actions struct {
	client *Client
}

// FindMany retrieves multiple {{$model.Name}} records.
func (a {{$model.Name}}Actions) FindMany(ctx context.Context, opts ...query.{{$model.Name}}QueryOption) ([]model.{{$model.Name}}, error) {
	cfg := query.Apply{{$model.Name}}Options(opts)
	q := "SELECT {{columnCSV $model}} FROM {{tableName $model}}"
	argIdx := 0
	where, args := build{{$model.Name}}Where(a.client, cfg.Wheres, &argIdx)
	if where != "" {
		q += " WHERE " + where
	}
	if len(cfg.OrderBys) > 0 {
		obs := make([]string, len(cfg.OrderBys))
		for i, ob := range cfg.OrderBys {
			obs[i] = ob.Field + " " + ob.Direction
		}
		q += " ORDER BY " + strings.Join(obs, ", ")
	}
	if cfg.Take != nil {
		q += fmt.Sprintf(" LIMIT %d", *cfg.Take)
	}
	if cfg.Skip != nil {
		q += fmt.Sprintf(" OFFSET %d", *cfg.Skip)
	}
	rows, err := a.client.executor.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("{{$model.Name}}.FindMany: %w", err)
	}
	defer rows.Close()
	var results []model.{{$model.Name}}
	for rows.Next() {
		var item model.{{$model.Name}}
		if err := rows.Scan({{scanFields $model}}); err != nil {
			return nil, fmt.Errorf("{{$model.Name}}.FindMany scan: %w", err)
		}
		results = append(results, item)
	}
	return results, rows.Err()
}

// FindFirst retrieves the first matching {{$model.Name}} record.
func (a {{$model.Name}}Actions) FindFirst(ctx context.Context, opts ...query.{{$model.Name}}QueryOption) (*model.{{$model.Name}}, error) {
	opts = append(opts, query.{{$model.Name}}TakeOption{N: 1})
	results, err := a.FindMany(ctx, opts...)
	if err != nil {
		return nil, err
	}
	if len(results) == 0 {
		return nil, nil
	}
	return &results[0], nil
}

// FindUnique retrieves a single {{$model.Name}} record by unique constraint.
func (a {{$model.Name}}Actions) FindUnique(ctx context.Context, where query.{{$model.Name}}WhereClause) (*model.{{$model.Name}}, error) {
	argIdx := 0
	whereSQL, args := build{{$model.Name}}Where(a.client, []query.{{$model.Name}}WhereClause{where}, &argIdx)
	q := "SELECT {{columnCSV $model}} FROM {{tableName $model}}"
	if whereSQL != "" {
		q += " WHERE " + whereSQL
	}
	q += " LIMIT 1"
	row := a.client.executor.QueryRowContext(ctx, q, args...)
	var item model.{{$model.Name}}
	if err := row.Scan({{scanFields $model}}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, fmt.Errorf("{{$model.Name}}.FindUnique: %w", err)
	}
	return &item, nil
}

// CreateOne creates a single {{$model.Name}} record.
func (a {{$model.Name}}Actions) CreateOne(ctx context.Context, sets ...query.{{$model.Name}}SetClause) (*model.{{$model.Name}}, error) {
	if len(sets) == 0 {
		return nil, fmt.Errorf("{{$model.Name}}.CreateOne: no fields provided")
	}
	cols := make([]string, len(sets))
	vals := make([]any, len(sets))
	phs := make([]string, len(sets))
	for i, s := range sets {
		cols[i] = s.Field
		vals[i] = s.Value
		phs[i] = a.client.placeholder(i + 1)
	}
	q := fmt.Sprintf("INSERT INTO {{tableName $model}} (%s) VALUES (%s)",
		strings.Join(cols, ", "), strings.Join(phs, ", "))
	if a.client.dialect == "postgresql" {
		q += " RETURNING {{columnCSV $model}}"
		row := a.client.executor.QueryRowContext(ctx, q, vals...)
		var item model.{{$model.Name}}
		if err := row.Scan({{scanFields $model}}); err != nil {
			return nil, fmt.Errorf("{{$model.Name}}.CreateOne: %w", err)
		}
		return &item, nil
	}
	result, err := a.client.executor.ExecContext(ctx, q, vals...)
	if err != nil {
		return nil, fmt.Errorf("{{$model.Name}}.CreateOne: %w", err)
	}
	_ = result
	return nil, nil
}

// CreateMany creates multiple {{$model.Name}} records.
func (a {{$model.Name}}Actions) CreateMany(ctx context.Context, data []query.{{$model.Name}}CreateInput) (int64, error) {
	if len(data) == 0 {
		return 0, nil
	}
	cols := []string{ {{scalarColNamesCSV $model}} }
	argIdx := 0
	var valueSets []string
	var args []any
	for _, d := range data {
		row := d.ScalarValues()
		phs := make([]string, len(row))
		for i, v := range row {
			argIdx++
			phs[i] = a.client.placeholder(argIdx)
			args = append(args, v)
		}
		valueSets = append(valueSets, "("+strings.Join(phs, ", ")+")")
	}
	q := fmt.Sprintf("INSERT INTO {{tableName $model}} (%s) VALUES %s",
		strings.Join(cols, ", "), strings.Join(valueSets, ", "))
	result, err := a.client.executor.ExecContext(ctx, q, args...)
	if err != nil {
		return 0, fmt.Errorf("{{$model.Name}}.CreateMany: %w", err)
	}
	return result.RowsAffected()
}

// UpdateOne updates a single {{$model.Name}} record matching the where clause.
func (a {{$model.Name}}Actions) UpdateOne(ctx context.Context, where query.{{$model.Name}}WhereClause, sets ...query.{{$model.Name}}SetClause) (*model.{{$model.Name}}, error) {
	if len(sets) == 0 {
		return nil, fmt.Errorf("{{$model.Name}}.UpdateOne: no fields to update")
	}
	argIdx := 0
	setParts := make([]string, len(sets))
	args := make([]any, 0, len(sets)+1)
	for i, s := range sets {
		argIdx++
		setParts[i] = s.Field + " = " + a.client.placeholder(argIdx)
		args = append(args, s.Value)
	}
	whereSQL, whereArgs := build{{$model.Name}}Where(a.client, []query.{{$model.Name}}WhereClause{where}, &argIdx)
	args = append(args, whereArgs...)
	q := fmt.Sprintf("UPDATE {{tableName $model}} SET %s", strings.Join(setParts, ", "))
	if whereSQL != "" {
		q += " WHERE " + whereSQL
	}
	if a.client.dialect == "postgresql" {
		q += " RETURNING {{columnCSV $model}}"
		row := a.client.executor.QueryRowContext(ctx, q, args...)
		var item model.{{$model.Name}}
		if err := row.Scan({{scanFields $model}}); err != nil {
			if err == sql.ErrNoRows {
				return nil, nil
			}
			return nil, fmt.Errorf("{{$model.Name}}.UpdateOne: %w", err)
		}
		return &item, nil
	}
	_, err := a.client.executor.ExecContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("{{$model.Name}}.UpdateOne: %w", err)
	}
	return nil, nil
}

// UpdateMany updates multiple {{$model.Name}} records matching the where clauses.
func (a {{$model.Name}}Actions) UpdateMany(ctx context.Context, wheres []query.{{$model.Name}}WhereClause, sets ...query.{{$model.Name}}SetClause) (int64, error) {
	if len(sets) == 0 {
		return 0, fmt.Errorf("{{$model.Name}}.UpdateMany: no fields to update")
	}
	argIdx := 0
	setParts := make([]string, len(sets))
	args := make([]any, 0, len(sets)+len(wheres))
	for i, s := range sets {
		argIdx++
		setParts[i] = s.Field + " = " + a.client.placeholder(argIdx)
		args = append(args, s.Value)
	}
	whereSQL, whereArgs := build{{$model.Name}}Where(a.client, wheres, &argIdx)
	args = append(args, whereArgs...)
	q := fmt.Sprintf("UPDATE {{tableName $model}} SET %s", strings.Join(setParts, ", "))
	if whereSQL != "" {
		q += " WHERE " + whereSQL
	}
	result, err := a.client.executor.ExecContext(ctx, q, args...)
	if err != nil {
		return 0, fmt.Errorf("{{$model.Name}}.UpdateMany: %w", err)
	}
	return result.RowsAffected()
}

// UpsertOne creates or updates a single {{$model.Name}} record.
func (a {{$model.Name}}Actions) UpsertOne(ctx context.Context, where query.{{$model.Name}}WhereClause, create []query.{{$model.Name}}SetClause, update []query.{{$model.Name}}SetClause) (*model.{{$model.Name}}, error) {
	if len(create) == 0 {
		return nil, fmt.Errorf("{{$model.Name}}.UpsertOne: no create fields provided")
	}
	argIdx := 0
	cols := make([]string, len(create))
	phs := make([]string, len(create))
	args := make([]any, 0, len(create)+len(update))
	for i, s := range create {
		cols[i] = s.Field
		argIdx++
		phs[i] = a.client.placeholder(argIdx)
		args = append(args, s.Value)
	}
	q := fmt.Sprintf("INSERT INTO {{tableName $model}} (%s) VALUES (%s)",
		strings.Join(cols, ", "), strings.Join(phs, ", "))
	if a.client.dialect == "mysql" {
		if len(update) > 0 {
			uParts := make([]string, len(update))
			for i, s := range update {
				argIdx++
				uParts[i] = s.Field + " = " + a.client.placeholder(argIdx)
				args = append(args, s.Value)
			}
			q += " ON DUPLICATE KEY UPDATE " + strings.Join(uParts, ", ")
		}
	} else {
		q += fmt.Sprintf(" ON CONFLICT (%s) DO", where.Field)
		if len(update) > 0 {
			uParts := make([]string, len(update))
			for i, s := range update {
				argIdx++
				uParts[i] = s.Field + " = " + a.client.placeholder(argIdx)
				args = append(args, s.Value)
			}
			q += " UPDATE SET " + strings.Join(uParts, ", ")
		} else {
			q += " NOTHING"
		}
	}
	if a.client.dialect == "postgresql" {
		q += " RETURNING {{columnCSV $model}}"
		row := a.client.executor.QueryRowContext(ctx, q, args...)
		var item model.{{$model.Name}}
		if err := row.Scan({{scanFields $model}}); err != nil {
			return nil, fmt.Errorf("{{$model.Name}}.UpsertOne: %w", err)
		}
		return &item, nil
	}
	_, err := a.client.executor.ExecContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("{{$model.Name}}.UpsertOne: %w", err)
	}
	return nil, nil
}

// DeleteOne deletes a single {{$model.Name}} record matching the where clause.
func (a {{$model.Name}}Actions) DeleteOne(ctx context.Context, where query.{{$model.Name}}WhereClause) (*model.{{$model.Name}}, error) {
	argIdx := 0
	whereSQL, args := build{{$model.Name}}Where(a.client, []query.{{$model.Name}}WhereClause{where}, &argIdx)
	q := "DELETE FROM {{tableName $model}}"
	if whereSQL != "" {
		q += " WHERE " + whereSQL
	}
	if a.client.dialect == "postgresql" {
		q += " RETURNING {{columnCSV $model}}"
		row := a.client.executor.QueryRowContext(ctx, q, args...)
		var item model.{{$model.Name}}
		if err := row.Scan({{scanFields $model}}); err != nil {
			if err == sql.ErrNoRows {
				return nil, nil
			}
			return nil, fmt.Errorf("{{$model.Name}}.DeleteOne: %w", err)
		}
		return &item, nil
	}
	_, err := a.client.executor.ExecContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("{{$model.Name}}.DeleteOne: %w", err)
	}
	return nil, nil
}

// DeleteMany deletes multiple {{$model.Name}} records matching the where clauses.
func (a {{$model.Name}}Actions) DeleteMany(ctx context.Context, wheres ...query.{{$model.Name}}WhereClause) (int64, error) {
	argIdx := 0
	whereSQL, args := build{{$model.Name}}Where(a.client, wheres, &argIdx)
	q := "DELETE FROM {{tableName $model}}"
	if whereSQL != "" {
		q += " WHERE " + whereSQL
	}
	result, err := a.client.executor.ExecContext(ctx, q, args...)
	if err != nil {
		return 0, fmt.Errorf("{{$model.Name}}.DeleteMany: %w", err)
	}
	return result.RowsAffected()
}

// Count returns the number of {{$model.Name}} records matching the where clauses.
func (a {{$model.Name}}Actions) Count(ctx context.Context, wheres ...query.{{$model.Name}}WhereClause) (int64, error) {
	argIdx := 0
	whereSQL, args := build{{$model.Name}}Where(a.client, wheres, &argIdx)
	q := "SELECT COUNT(*) FROM {{tableName $model}}"
	if whereSQL != "" {
		q += " WHERE " + whereSQL
	}
	var count int64
	if err := a.client.executor.QueryRowContext(ctx, q, args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("{{$model.Name}}.Count: %w", err)
	}
	return count, nil
}

// Aggregate computes aggregate values for {{$model.Name}}.
func (a {{$model.Name}}Actions) Aggregate(ctx context.Context, opts ...query.{{$model.Name}}AggregateOption) (*query.{{$model.Name}}AggregateResult, error) {
	selParts := []string{"COUNT(*)"}
	for _, opt := range opts {
		selParts = append(selParts, fmt.Sprintf("%s(%s)", strings.ToUpper(opt.Fn), opt.Field))
	}
	q := fmt.Sprintf("SELECT %s FROM {{tableName $model}}", strings.Join(selParts, ", "))
	row := a.client.executor.QueryRowContext(ctx, q)
	result := &query.{{$model.Name}}AggregateResult{
		Avg: make(map[string]*float64),
		Sum: make(map[string]*float64),
		Min: make(map[string]any),
		Max: make(map[string]any),
	}
	aggVals := make([]sql.NullFloat64, len(opts))
	scanDest := make([]any, 0, 1+len(opts))
	scanDest = append(scanDest, &result.Count)
	for i := range opts {
		scanDest = append(scanDest, &aggVals[i])
	}
	if err := row.Scan(scanDest...); err != nil {
		return nil, fmt.Errorf("{{$model.Name}}.Aggregate: %w", err)
	}
	for i, opt := range opts {
		if aggVals[i].Valid {
			v := aggVals[i].Float64
			switch opt.Fn {
			case "avg":
				result.Avg[opt.Field] = &v
			case "sum":
				result.Sum[opt.Field] = &v
			case "min":
				result.Min[opt.Field] = v
			case "max":
				result.Max[opt.Field] = v
			}
		}
	}
	return result, nil
}

// GroupBy performs a GROUP BY query on {{$model.Name}}.
func (a {{$model.Name}}Actions) GroupBy(ctx context.Context, fields []string, opts ...query.{{$model.Name}}AggregateOption) ([]query.{{$model.Name}}GroupByResult, error) {
	selParts := make([]string, 0, len(fields)+1+len(opts))
	selParts = append(selParts, fields...)
	selParts = append(selParts, "COUNT(*)")
	for _, opt := range opts {
		selParts = append(selParts, fmt.Sprintf("%s(%s)", strings.ToUpper(opt.Fn), opt.Field))
	}
	q := fmt.Sprintf("SELECT %s FROM {{tableName $model}} GROUP BY %s",
		strings.Join(selParts, ", "), strings.Join(fields, ", "))
	rows, err := a.client.executor.QueryContext(ctx, q)
	if err != nil {
		return nil, fmt.Errorf("{{$model.Name}}.GroupBy: %w", err)
	}
	defer rows.Close()
	var results []query.{{$model.Name}}GroupByResult
	for rows.Next() {
		r := query.{{$model.Name}}GroupByResult{
			Group: make(map[string]any),
			Avg:   make(map[string]*float64),
			Sum:   make(map[string]*float64),
			Min:   make(map[string]any),
			Max:   make(map[string]any),
		}
		groupVals := make([]any, len(fields))
		scanDest := make([]any, 0, len(fields)+1+len(opts))
		for i := range fields {
			groupVals[i] = new(any)
			scanDest = append(scanDest, groupVals[i])
		}
		scanDest = append(scanDest, &r.Count)
		aggVals := make([]sql.NullFloat64, len(opts))
		for i := range opts {
			scanDest = append(scanDest, &aggVals[i])
		}
		if err := rows.Scan(scanDest...); err != nil {
			return nil, fmt.Errorf("{{$model.Name}}.GroupBy scan: %w", err)
		}
		for i, f := range fields {
			r.Group[f] = *(groupVals[i].(*any))
		}
		for i, opt := range opts {
			if aggVals[i].Valid {
				v := aggVals[i].Float64
				switch opt.Fn {
				case "avg":
					r.Avg[opt.Field] = &v
				case "sum":
					r.Sum[opt.Field] = &v
				case "min":
					r.Min[opt.Field] = v
				case "max":
					r.Max[opt.Field] = v
				}
			}
		}
		results = append(results, r)
	}
	return results, rows.Err()
}
{{end}}
`
