package golang

// Template for enum types.
var enumsTmpl = `// Code generated by GCO ORM. DO NOT EDIT.
package model

{{range .Enums}}
// {{.Name}} represents the {{.Name}} enum type.
type {{.Name}} string

const (
{{- range .Values}}
	{{$.Enums}}{{.Name}} {{$.Enums}}{{$.Enums}} = "{{.Name}}"
{{- end}}
)
{{end}}
`

func init() {
	// Fix the enums template to use proper enum references.
	enumsTmpl = `// Code generated by GCO ORM. DO NOT EDIT.
package model

{{range $enum := .Enums}}
// {{$enum.Name}} represents the {{$enum.Name}} enum type.
type {{$enum.Name}} string

const (
{{- range $val := $enum.Values}}
	{{$enum.Name}}{{$val.Name}} {{$enum.Name}} = "{{$val.Name}}"
{{- end}}
)

// Valid{{$enum.Name}}Values returns all valid values for the {{$enum.Name}} enum.
func Valid{{$enum.Name}}Values() []{{$enum.Name}} {
	return []{{$enum.Name}}{
{{- range $val := $enum.Values}}
		{{$enum.Name}}{{$val.Name}},
{{- end}}
	}
}
{{end}}
`
}

// Template for model struct types.
var modelsTmpl = `// Code generated by GCO ORM. DO NOT EDIT.
package model

{{- $needsTime := false}}
{{- $needsJSON := false}}
{{- range .Models}}
{{- range .Fields}}
{{- if and (eq .Type 0) (eq .ScalarType "DateTime")}}{{$needsTime = true}}{{end}}
{{- if and (eq .Type 0) (eq .ScalarType "Json")}}{{$needsJSON = true}}{{end}}
{{- end}}
{{- end}}

{{if or $needsTime $needsJSON}}
import (
{{- if $needsTime}}
	"time"
{{- end}}
{{- if $needsJSON}}
	"encoding/json"
{{- end}}
)
{{end}}

{{range $model := .Models}}
// {{$model.Name}} represents the {{$model.Name}} model.
type {{$model.Name}} struct {
{{- range $field := $model.Fields}}
{{- if ne $field.Type 2}}
	{{upper $field.Name}} {{goType $field}} ` + "`" + `db:"{{columnName $field}}" json:"{{lower $field.Name}}"` + "`" + `
{{- end}}
{{- end}}
{{- range $field := $model.Fields}}
{{- if eq $field.Type 2}}
	{{upper $field.Name}} {{goType $field}} ` + "`" + `db:"-" json:"{{lower $field.Name}},omitempty"` + "`" + `
{{- end}}
{{- end}}
}
{{end}}
`

// Template for query builder per model.
var queryTmpl = `// Code generated by GCO ORM. DO NOT EDIT.
package query

{{- $needsTime := false}}
{{- $needsJSON := false}}
{{- range .Model.Fields}}
{{- if and (eq .Type 0) (eq .ScalarType "DateTime")}}{{$needsTime = true}}{{end}}
{{- if and (eq .Type 0) (eq .ScalarType "Json")}}{{$needsJSON = true}}{{end}}
{{- end}}

{{if or $needsTime $needsJSON (hasEnumFields .Model)}}
import (
{{- if $needsTime}}
	"time"
{{- end}}
{{- if $needsJSON}}
	"encoding/json"
{{- end}}
{{- if hasEnumFields .Model}}
	"{{.ModelImport}}"
{{- end}}
)
{{end}}

// {{.Model.Name}}QueryOption configures a {{.Model.Name}} query.
type {{.Model.Name}}QueryOption interface {
	apply{{.Model.Name}}Query(*{{.Model.Name}}QueryConfig)
}

// {{.Model.Name}}QueryConfig collects query parameters for {{.Model.Name}}.
type {{.Model.Name}}QueryConfig struct {
	Wheres   []{{.Model.Name}}WhereClause
	OrderBys []{{.Model.Name}}OrderByClause
	Includes []{{.Model.Name}}IncludeClause
	Take     *int
	Skip     *int
}

// Apply{{.Model.Name}}Options applies a list of query options to produce a QueryConfig.
func Apply{{.Model.Name}}Options(opts []{{.Model.Name}}QueryOption) {{.Model.Name}}QueryConfig {
	var cfg {{.Model.Name}}QueryConfig
	for _, opt := range opts {
		opt.apply{{.Model.Name}}Query(&cfg)
	}
	return cfg
}

// {{.Model.Name}}Query is the namespace for {{.Model.Name}} query operations.
type {{.Model.Name}}Query struct {
{{- range $field := .Model.Fields}}
{{- if ne $field.Type 2}}
	{{upper $field.Name}} {{lower $.Model.Name}}{{upper $field.Name}}Field
{{- end}}
{{- if eq $field.Type 2}}
	{{upper $field.Name}} {{lower $.Model.Name}}{{upper $field.Name}}Relation
{{- end}}
{{- end}}
}

const {{.Model.Name}}Table = "{{tableName .Model}}"
{{- range $field := .Model.Fields}}
{{- if ne $field.Type 2}}
const {{$.Model.Name}}{{upper $field.Name}}Column = "{{columnName $field}}"
{{- end}}
{{- end}}

// {{.Model.Name}}Query provides query building methods for the {{.Model.Name}} model.
var {{.Model.Name}} = {{.Model.Name}}Query{
{{- range $field := .Model.Fields}}
	{{upper $field.Name}}: {{lower $.Model.Name}}{{upper $field.Name}}{{if eq $field.Type 2}}Relation{{else}}Field{{end}}{},
{{- end}}
}

// {{.Model.Name}}WhereClause represents a WHERE condition for {{.Model.Name}}.
type {{.Model.Name}}WhereClause struct {
	Field    string
	Operator string
	Value    any
}

func (w {{.Model.Name}}WhereClause) apply{{.Model.Name}}Query(c *{{.Model.Name}}QueryConfig) {
	c.Wheres = append(c.Wheres, w)
}

// {{.Model.Name}}OrderByClause represents an ORDER BY clause for {{.Model.Name}}.
type {{.Model.Name}}OrderByClause struct {
	Field     string
	Direction string // "ASC" or "DESC"
}

func (o {{.Model.Name}}OrderByClause) apply{{.Model.Name}}Query(c *{{.Model.Name}}QueryConfig) {
	c.OrderBys = append(c.OrderBys, o)
}

// {{.Model.Name}}IncludeClause represents an include directive for {{.Model.Name}}.
type {{.Model.Name}}IncludeClause struct {
	Relation string
}

func (i {{.Model.Name}}IncludeClause) apply{{.Model.Name}}Query(c *{{.Model.Name}}QueryConfig) {
	c.Includes = append(c.Includes, i)
}

// {{.Model.Name}}TakeOption limits the number of results.
type {{.Model.Name}}TakeOption struct{ N int }

func (t {{.Model.Name}}TakeOption) apply{{.Model.Name}}Query(c *{{.Model.Name}}QueryConfig) {
	c.Take = &t.N
}

// {{.Model.Name}}SkipOption skips a number of results.
type {{.Model.Name}}SkipOption struct{ N int }

func (s {{.Model.Name}}SkipOption) apply{{.Model.Name}}Query(c *{{.Model.Name}}QueryConfig) {
	c.Skip = &s.N
}

// Where creates a composite WHERE condition from multiple clauses.
func ({{.Model.Name}}Query) Where(clauses ...{{.Model.Name}}WhereClause) []{{.Model.Name}}WhereClause {
	return clauses
}

// OrderBy creates an ORDER BY clause.
func ({{.Model.Name}}Query) OrderBy(clause {{.Model.Name}}OrderByClause) {{.Model.Name}}OrderByClause {
	return clause
}

// Include creates an include directive.
func ({{.Model.Name}}Query) Include(clauses ...{{.Model.Name}}IncludeClause) []{{.Model.Name}}IncludeClause {
	return clauses
}

// Take returns a take (limit) option.
func ({{.Model.Name}}Query) Take(n int) {{.Model.Name}}TakeOption {
	return {{.Model.Name}}TakeOption{N: n}
}

// Skip returns a skip (offset) option.
func ({{.Model.Name}}Query) Skip(n int) {{.Model.Name}}SkipOption {
	return {{.Model.Name}}SkipOption{N: n}
}

// AND combines multiple WHERE clauses with AND logic.
func ({{.Model.Name}}Query) AND(clauses ...{{.Model.Name}}WhereClause) {{.Model.Name}}WhereClause {
	return {{.Model.Name}}WhereClause{Field: "__AND__", Value: clauses}
}

// OR combines multiple WHERE clauses with OR logic.
func ({{.Model.Name}}Query) OR(clauses ...{{.Model.Name}}WhereClause) {{.Model.Name}}WhereClause {
	return {{.Model.Name}}WhereClause{Field: "__OR__", Value: clauses}
}

// NOT negates a WHERE clause.
func ({{.Model.Name}}Query) NOT(clause {{.Model.Name}}WhereClause) {{.Model.Name}}WhereClause {
	return {{.Model.Name}}WhereClause{Field: "__NOT__", Value: clause}
}

// Cursor creates a cursor-based pagination condition.
func ({{.Model.Name}}Query) Cursor(field string, value any) {{.Model.Name}}WhereClause {
	return {{.Model.Name}}WhereClause{Field: field, Operator: ">", Value: value}
}

{{range $field := .Model.Fields}}
{{- if ne $field.Type 2}}
// {{upper $field.Name}}Field provides query operations for the {{$field.Name}} field.
type {{lower $.Model.Name}}{{upper $field.Name}}Field struct{}

// Equals creates an equality condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Equals(v {{queryGoType $field}}) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{columnName $field}}", Operator: "=", Value: v}
}

// Not creates a not-equal condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Not(v {{queryGoType $field}}) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{columnName $field}}", Operator: "!=", Value: v}
}

// In creates an IN condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) In(vals ...{{queryGoType $field}}) {{$.Model.Name}}WhereClause {
	iVals := make([]any, len(vals))
	for i, v := range vals {
		iVals[i] = v
	}
	return {{$.Model.Name}}WhereClause{Field: "{{columnName $field}}", Operator: "IN", Value: iVals}
}

// NotIn creates a NOT IN condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) NotIn(vals ...{{queryGoType $field}}) {{$.Model.Name}}WhereClause {
	iVals := make([]any, len(vals))
	for i, v := range vals {
		iVals[i] = v
	}
	return {{$.Model.Name}}WhereClause{Field: "{{columnName $field}}", Operator: "NOT IN", Value: iVals}
}

{{- if or (eq $field.ScalarType "Int") (eq $field.ScalarType "BigInt") (eq $field.ScalarType "Float") (eq $field.ScalarType "Decimal") (eq $field.ScalarType "DateTime")}}

// Lt creates a less-than condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Lt(v {{queryGoType $field}}) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{columnName $field}}", Operator: "<", Value: v}
}

// Lte creates a less-than-or-equal condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Lte(v {{queryGoType $field}}) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{columnName $field}}", Operator: "<=", Value: v}
}

// Gt creates a greater-than condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Gt(v {{queryGoType $field}}) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{columnName $field}}", Operator: ">", Value: v}
}

// Gte creates a greater-than-or-equal condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Gte(v {{queryGoType $field}}) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{columnName $field}}", Operator: ">=", Value: v}
}
{{end}}

{{- if eq $field.ScalarType "String"}}

// Contains creates a LIKE '%v%' condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Contains(v string) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{columnName $field}}", Operator: "CONTAINS", Value: v}
}

// StartsWith creates a LIKE 'v%' condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) StartsWith(v string) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{columnName $field}}", Operator: "STARTS_WITH", Value: v}
}

// EndsWith creates a LIKE '%v' condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) EndsWith(v string) {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{columnName $field}}", Operator: "ENDS_WITH", Value: v}
}
{{end}}

{{- if $field.IsOptional}}

// IsNull creates an IS NULL condition.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) IsNull() {{$.Model.Name}}WhereClause {
	return {{$.Model.Name}}WhereClause{Field: "{{columnName $field}}", Operator: "IS NULL", Value: nil}
}
{{end}}

// Set creates a set operation for create/update.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Set(v {{if $field.IsOptional}}{{setGoType $field}}{{else}}{{queryGoType $field}}{{end}}) {{$.Model.Name}}SetClause {
	return {{$.Model.Name}}SetClause{Field: "{{columnName $field}}", Value: v}
}

{{- if $field.IsOptional}}

// SetNull sets the field to NULL.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) SetNull() {{$.Model.Name}}SetClause {
	return {{$.Model.Name}}SetClause{Field: "{{columnName $field}}", Value: nil}
}
{{end}}

// Asc returns an ascending order clause for this field.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Asc() {{$.Model.Name}}OrderByClause {
	return {{$.Model.Name}}OrderByClause{Field: "{{columnName $field}}", Direction: "ASC"}
}

// Desc returns a descending order clause for this field.
func ({{lower $.Model.Name}}{{upper $field.Name}}Field) Desc() {{$.Model.Name}}OrderByClause {
	return {{$.Model.Name}}OrderByClause{Field: "{{columnName $field}}", Direction: "DESC"}
}
{{end}}
{{- if eq $field.Type 2}}
// {{upper $field.Name}}Relation provides relation query helpers for {{$field.Name}}.
type {{lower $.Model.Name}}{{upper $field.Name}}Relation struct{}

// Fetch creates an include clause to fetch related {{$field.Name}}.
func ({{lower $.Model.Name}}{{upper $field.Name}}Relation) Fetch() {{$.Model.Name}}IncludeClause {
	return {{$.Model.Name}}IncludeClause{Relation: "{{$field.Name}}"}
}
{{end}}
{{end}}

// {{.Model.Name}}SetClause represents a field set operation for create/update.
type {{.Model.Name}}SetClause struct {
	Field string
	Value any
}

// {{.Model.Name}}AggregateOption specifies an aggregate function to compute.
type {{.Model.Name}}AggregateOption struct {
	Fn    string
	Field string
}

// {{.Model.Name}}AggregateResult holds the result of an aggregate query.
type {{.Model.Name}}AggregateResult struct {
	Count int64
	Avg   map[string]*float64
	Sum   map[string]*float64
	Min   map[string]any
	Max   map[string]any
}

// {{.Model.Name}}GroupByResult holds a single row from a GROUP BY query.
type {{.Model.Name}}GroupByResult struct {
	Group map[string]any
	Count int64
	Avg   map[string]*float64
	Sum   map[string]*float64
	Min   map[string]any
	Max   map[string]any
}

// {{.Model.Name}}CreateInput holds data for creating a {{.Model.Name}} record.
type {{.Model.Name}}CreateInput struct {
{{- range scalarCols .Model}}
	{{upper .Name}} {{if .IsOptional}}*{{end}}{{queryGoType .}}
{{- end}}
{{- range .Model.Fields}}
{{- if eq .Type 2}}
	{{upper .Name}} *{{.ModelType}}CreateNestedInput
{{- end}}
{{- end}}
}

// ScalarValues returns the scalar field values in column order.
func (d {{.Model.Name}}CreateInput) ScalarValues() []any {
	return []any{ {{createInputValues .Model}} }
}

// {{.Model.Name}}CreateNestedInput supports nested creates and connects.
type {{.Model.Name}}CreateNestedInput struct {
	Create  *{{.Model.Name}}CreateInput
	Connect *{{.Model.Name}}WhereUniqueInput
}

// {{.Model.Name}}WhereUniqueInput identifies a unique {{.Model.Name}} record.
type {{.Model.Name}}WhereUniqueInput struct {
{{- range scalarCols .Model}}
{{- if or .IsID .IsUnique}}
	{{upper .Name}} *{{queryGoType .}}
{{- end}}
{{- end}}
}
`

// Template for the client entry point.
var clientTmpl = `// Code generated by GCO ORM. DO NOT EDIT.
package client

import (
	"context"
	"database/sql"
{{- if .Models}}
	"fmt"
	"reflect"
	"strings"

	"{{.BaseImport}}/model"
	"{{.BaseImport}}/query"
{{- end}}
)

{{- if .Models}}

// querier is the common interface for *sql.DB and *sql.Tx.
type querier interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row
}
{{- end}}

// Client is the main entry point for database operations.
type Client struct {
	db *sql.DB
{{- if .Models}}
	executor querier
	dialect  string
{{- end}}
{{- range .Models}}
	{{.Name}} {{.Name}}Actions
{{- end}}
}

// New creates a new Client from a database connection.
func New(db *sql.DB{{if .Models}}, opts ...Option{{end}}) *Client {
	c := &Client{db: db{{if .Models}}, executor: db, dialect: "postgresql"{{end}}}
{{- if .Models}}
	for _, opt := range opts {
		opt(c)
	}
{{- end}}
{{- range .Models}}
	c.{{.Name}} = {{.Name}}Actions{client: c}
{{- end}}
	return c
}

{{- if .Models}}

// Option configures the Client.
type Option func(*Client)

// WithDialect sets the SQL dialect ("postgresql", "mysql", "sqlite").
func WithDialect(d string) Option {
	return func(c *Client) { c.dialect = d }
}
{{- end}}

// Close closes the underlying database connection.
func (c *Client) Close() error {
	return c.db.Close()
}

// DB returns the underlying *sql.DB.
func (c *Client) DB() *sql.DB {
	return c.db
}

{{- if .Models}}

// placeholder returns the parameter placeholder for the nth parameter (1-based).
func (c *Client) placeholder(n int) string {
	if c.dialect == "postgresql" {
		return fmt.Sprintf("$%d", n)
	}
	return "?"
}

func scanRowsToMaps(rows *sql.Rows) ([]map[string]any, error) {
	cols, err := rows.Columns()
	if err != nil {
		return nil, err
	}
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		dest := make([]any, len(cols))
		for i := range values {
			dest[i] = &values[i]
		}
		if err := rows.Scan(dest...); err != nil {
			return nil, err
		}
		row := make(map[string]any, len(cols))
		for i, col := range cols {
			if b, ok := values[i].([]byte); ok {
				row[col] = string(b)
				continue
			}
			row[col] = values[i]
		}
		results = append(results, row)
	}
	return results, rows.Err()
}

func scanRowsToStructs[T any](rows *sql.Rows) ([]T, error) {
	cols, err := rows.Columns()
	if err != nil {
		return nil, err
	}

	var sample T
	typ := reflect.TypeOf(sample)
	if typ.Kind() != reflect.Struct {
		return nil, fmt.Errorf("Raw: destination type must be a struct, got %s", typ.Kind())
	}

	fieldByColumn := make(map[string]int)
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		if field.PkgPath != "" {
			continue
		}
		dbName := field.Tag.Get("db")
		if comma := strings.Index(dbName, ","); comma >= 0 {
			dbName = dbName[:comma]
		}
		if dbName == "-" {
			continue
		}
		if dbName != "" {
			fieldByColumn[dbName] = i
		}
		fieldByColumn[field.Name] = i
	}

	var results []T
	for rows.Next() {
		var item T
		value := reflect.ValueOf(&item).Elem()
		dest := make([]any, len(cols))
		for i, col := range cols {
			if fieldIndex, ok := fieldByColumn[col]; ok {
				field := value.Field(fieldIndex)
				if field.CanAddr() {
					dest[i] = field.Addr().Interface()
					continue
				}
			}
			var discard any
			dest[i] = &discard
		}
		if err := rows.Scan(dest...); err != nil {
			return nil, err
		}
		results = append(results, item)
	}
	return results, rows.Err()
}

func escapeLikePattern(s string) string {
	replacer := strings.NewReplacer("\\", "\\\\", "%", "\\%", "_", "\\_")
	return replacer.Replace(s)
}

// Raw executes a custom SELECT query and scans rows into T using db tags.
func Raw[T any](ctx context.Context, c *Client, query string, args ...any) ([]T, error) {
	rows, err := c.executor.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanRowsToStructs[T](rows)
}

// RawRows executes a custom SELECT query and returns row maps keyed by column name.
func (c *Client) RawRows(ctx context.Context, query string, args ...any) ([]map[string]any, error) {
	rows, err := c.executor.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanRowsToMaps(rows)
}

// RawExec executes custom SQL and returns affected rows.
func (c *Client) RawExec(ctx context.Context, query string, args ...any) (int64, error) {
	result, err := c.executor.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
{{- end}}

// Tx executes a function within a database transaction.
// If the function returns nil, the transaction is committed.
// If the function returns an error, the transaction is rolled back.
func (c *Client) Tx(ctx context.Context, fn func(tx *Client) error) error {
	sqlTx, err := c.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}

	txClient := &Client{db: c.db{{if .Models}}, executor: sqlTx, dialect: c.dialect{{end}}}
{{- range .Models}}
	txClient.{{.Name}} = {{.Name}}Actions{client: txClient}
{{- end}}

	defer func() {
		if p := recover(); p != nil {
			_ = sqlTx.Rollback()
			panic(p)
		}
	}()

	if err := fn(txClient); err != nil {
		_ = sqlTx.Rollback()
		return err
	}
	return sqlTx.Commit()
}

{{range $model := .Models}}
// build{{$model.Name}}Where recursively builds a WHERE clause string and arguments.
func build{{$model.Name}}Where(c *Client, wheres []query.{{$model.Name}}WhereClause, argIdx *int) (string, []any) {
	var parts []string
	var args []any
	for _, w := range wheres {
		switch w.Field {
		case "__AND__":
			if subs, ok := w.Value.([]query.{{$model.Name}}WhereClause); ok {
				sub, subArgs := build{{$model.Name}}Where(c, subs, argIdx)
				if sub != "" {
					parts = append(parts, "("+sub+")")
				}
				args = append(args, subArgs...)
			}
		case "__OR__":
			if subs, ok := w.Value.([]query.{{$model.Name}}WhereClause); ok {
				var orParts []string
				for _, sc := range subs {
					sub, subArgs := build{{$model.Name}}Where(c, []query.{{$model.Name}}WhereClause{sc}, argIdx)
					if sub != "" {
						orParts = append(orParts, sub)
					}
					args = append(args, subArgs...)
				}
				if len(orParts) > 0 {
					parts = append(parts, "("+strings.Join(orParts, " OR ")+")")
				}
			}
		case "__NOT__":
			if sc, ok := w.Value.(query.{{$model.Name}}WhereClause); ok {
				sub, subArgs := build{{$model.Name}}Where(c, []query.{{$model.Name}}WhereClause{sc}, argIdx)
				if sub != "" {
					parts = append(parts, "NOT ("+sub+")")
				}
				args = append(args, subArgs...)
			}
		default:
			switch w.Operator {
			case "IS NULL":
				parts = append(parts, w.Field+" IS NULL")
			case "IN", "NOT IN":
				if vals, ok := w.Value.([]any); ok {
					if len(vals) == 0 {
						if w.Operator == "IN" {
							parts = append(parts, "1 = 0")
						} else {
							parts = append(parts, "1 = 1")
						}
					} else {
						phs := make([]string, len(vals))
						for i, v := range vals {
							*argIdx++
							phs[i] = c.placeholder(*argIdx)
							args = append(args, v)
						}
						parts = append(parts, w.Field+" "+w.Operator+" ("+strings.Join(phs, ", ")+")")
					}
				}
			case "CONTAINS":
				*argIdx++
				parts = append(parts, w.Field+" LIKE "+c.placeholder(*argIdx)+" ESCAPE '\\'")
				args = append(args, "%"+escapeLikePattern(fmt.Sprint(w.Value))+"%")
			case "STARTS_WITH":
				*argIdx++
				parts = append(parts, w.Field+" LIKE "+c.placeholder(*argIdx)+" ESCAPE '\\'")
				args = append(args, escapeLikePattern(fmt.Sprint(w.Value))+"%")
			case "ENDS_WITH":
				*argIdx++
				parts = append(parts, w.Field+" LIKE "+c.placeholder(*argIdx)+" ESCAPE '\\'")
				args = append(args, "%"+escapeLikePattern(fmt.Sprint(w.Value)))
			default:
				*argIdx++
				parts = append(parts, w.Field+" "+w.Operator+" "+c.placeholder(*argIdx))
				args = append(args, w.Value)
			}
		}
	}
	return strings.Join(parts, " AND "), args
}

// {{$model.Name}}Actions provides database operations for the {{$model.Name}} model.
type {{$model.Name}}Actions struct {
	client *Client
}

// {{$model.Name}}CreateBuilder builds a {{$model.Name}} create operation incrementally.
type {{$model.Name}}CreateBuilder struct {
	action {{$model.Name}}Actions
	sets   []query.{{$model.Name}}SetClause
}

// Create starts a staged {{$model.Name}} create operation.
func (a {{$model.Name}}Actions) Create() {{$model.Name}}CreateBuilder {
	return {{$model.Name}}CreateBuilder{action: a}
}

// Set appends field assignments to the staged create operation.
func (b {{$model.Name}}CreateBuilder) Set(sets ...query.{{$model.Name}}SetClause) {{$model.Name}}CreateBuilder {
	next := {{$model.Name}}CreateBuilder{
		action: b.action,
		sets:   make([]query.{{$model.Name}}SetClause, 0, len(b.sets)+len(sets)),
	}
	next.sets = append(next.sets, b.sets...)
	next.sets = append(next.sets, sets...)
	return next
}

// Do executes the staged create operation.
func (b {{$model.Name}}CreateBuilder) Do(ctx context.Context) (*model.{{$model.Name}}, error) {
	return b.action.CreateOne(ctx, b.sets...)
}

// {{$model.Name}}CreateManyBuilder builds a bulk {{$model.Name}} insert operation.
type {{$model.Name}}CreateManyBuilder struct {
	action            {{$model.Name}}Actions
	data              []query.{{$model.Name}}CreateInput
	conflictDoNothing bool
	conflictColumns   []string
	returningColumns  []string
	batchSize         int
}

// BulkCreate starts a staged bulk {{$model.Name}} insert operation.
func (a {{$model.Name}}Actions) BulkCreate(data []query.{{$model.Name}}CreateInput) {{$model.Name}}CreateManyBuilder {
	return {{$model.Name}}CreateManyBuilder{action: a, data: data}
}

// OnConflictDoNothing makes duplicate rows no-op instead of failing.
func (b {{$model.Name}}CreateManyBuilder) OnConflictDoNothing(columns ...string) {{$model.Name}}CreateManyBuilder {
	next := b
	next.conflictDoNothing = true
	next.conflictColumns = append([]string(nil), columns...)
	return next
}

// Returning sets the columns returned by DoReturningValues.
func (b {{$model.Name}}CreateManyBuilder) Returning(columns ...string) {{$model.Name}}CreateManyBuilder {
	next := b
	next.returningColumns = append([]string(nil), columns...)
	return next
}

// BatchSize limits how many rows are inserted per statement.
func (b {{$model.Name}}CreateManyBuilder) BatchSize(n int) {{$model.Name}}CreateManyBuilder {
	next := b
	next.batchSize = n
	return next
}

// Do executes the bulk insert and returns total affected rows.
func (b {{$model.Name}}CreateManyBuilder) Do(ctx context.Context) (int64, error) {
	if len(b.data) == 0 {
		return 0, nil
	}
	batchSize := b.batchSize
	if batchSize <= 0 || batchSize > len(b.data) {
		batchSize = len(b.data)
	}
	var total int64
	for start := 0; start < len(b.data); start += batchSize {
		end := start + batchSize
		if end > len(b.data) {
			end = len(b.data)
		}
		q, args := b.action.build{{$model.Name}}CreateManySQL(b.data[start:end], b.conflictDoNothing, b.conflictColumns, nil)
		result, err := b.action.client.executor.ExecContext(ctx, q, args...)
		if err != nil {
			return total, fmt.Errorf("{{$model.Name}}.BulkCreate: %w", err)
		}
		n, err := result.RowsAffected()
		if err != nil {
			return total, fmt.Errorf("{{$model.Name}}.BulkCreate rows affected: %w", err)
		}
		total += n
	}
	return total, nil
}

// DoReturning executes the bulk insert and returns inserted rows.
func (b {{$model.Name}}CreateManyBuilder) DoReturning(ctx context.Context) ([]model.{{$model.Name}}, error) {
	if b.action.client.dialect != "postgresql" {
		return nil, fmt.Errorf("{{$model.Name}}.BulkCreate.DoReturning: RETURNING is only supported for postgresql")
	}
	if len(b.returningColumns) > 0 {
		return nil, fmt.Errorf("{{$model.Name}}.BulkCreate.DoReturning: custom returning columns require DoReturningValues")
	}
	if len(b.data) == 0 {
		return nil, nil
	}
	batchSize := b.batchSize
	if batchSize <= 0 || batchSize > len(b.data) {
		batchSize = len(b.data)
	}
	var results []model.{{$model.Name}}
	for start := 0; start < len(b.data); start += batchSize {
		end := start + batchSize
		if end > len(b.data) {
			end = len(b.data)
		}
		q, args := b.action.build{{$model.Name}}CreateManySQL(b.data[start:end], b.conflictDoNothing, b.conflictColumns, []string{ {{scalarColNamesCSV $model}} })
		rows, err := b.action.client.executor.QueryContext(ctx, q, args...)
		if err != nil {
			return nil, fmt.Errorf("{{$model.Name}}.BulkCreate.DoReturning: %w", err)
		}
		for rows.Next() {
			var item model.{{$model.Name}}
			if err := rows.Scan({{scanFields $model}}); err != nil {
				_ = rows.Close()
				return nil, fmt.Errorf("{{$model.Name}}.BulkCreate.DoReturning scan: %w", err)
			}
			results = append(results, item)
		}
		if err := rows.Err(); err != nil {
			_ = rows.Close()
			return nil, fmt.Errorf("{{$model.Name}}.BulkCreate.DoReturning rows: %w", err)
		}
		if err := rows.Close(); err != nil {
			return nil, fmt.Errorf("{{$model.Name}}.BulkCreate.DoReturning close: %w", err)
		}
	}
	return results, nil
}

// DoReturningValues executes the bulk insert and returns selected column values.
func (b {{$model.Name}}CreateManyBuilder) DoReturningValues(ctx context.Context) ([]map[string]any, error) {
	if b.action.client.dialect != "postgresql" {
		return nil, fmt.Errorf("{{$model.Name}}.BulkCreate.DoReturningValues: RETURNING is only supported for postgresql")
	}
	if len(b.data) == 0 {
		return nil, nil
	}
	returningColumns := b.returningColumns
	if len(returningColumns) == 0 {
		returningColumns = []string{ {{scalarColNamesCSV $model}} }
	}
	batchSize := b.batchSize
	if batchSize <= 0 || batchSize > len(b.data) {
		batchSize = len(b.data)
	}
	var results []map[string]any
	for start := 0; start < len(b.data); start += batchSize {
		end := start + batchSize
		if end > len(b.data) {
			end = len(b.data)
		}
		q, args := b.action.build{{$model.Name}}CreateManySQL(b.data[start:end], b.conflictDoNothing, b.conflictColumns, returningColumns)
		rows, err := b.action.client.executor.QueryContext(ctx, q, args...)
		if err != nil {
			return nil, fmt.Errorf("{{$model.Name}}.BulkCreate.DoReturningValues: %w", err)
		}
		batch, err := scanRowsToMaps(rows)
		closeErr := rows.Close()
		if err != nil {
			return nil, fmt.Errorf("{{$model.Name}}.BulkCreate.DoReturningValues scan: %w", err)
		}
		if closeErr != nil {
			return nil, fmt.Errorf("{{$model.Name}}.BulkCreate.DoReturningValues close: %w", closeErr)
		}
		results = append(results, batch...)
	}
	return results, nil
}

// {{$model.Name}}QueryBuilder builds a {{$model.Name}} query incrementally.
type {{$model.Name}}QueryBuilder struct {
	action {{$model.Name}}Actions
	opts   []query.{{$model.Name}}QueryOption
}

// Query starts a staged {{$model.Name}} query.
func (a {{$model.Name}}Actions) Query() {{$model.Name}}QueryBuilder {
	return {{$model.Name}}QueryBuilder{action: a}
}

func (b {{$model.Name}}QueryBuilder) withOptions(opts ...query.{{$model.Name}}QueryOption) {{$model.Name}}QueryBuilder {
	next := {{$model.Name}}QueryBuilder{
		action: b.action,
		opts:   make([]query.{{$model.Name}}QueryOption, 0, len(b.opts)+len(opts)),
	}
	next.opts = append(next.opts, b.opts...)
	next.opts = append(next.opts, opts...)
	return next
}

// Where appends WHERE clauses to the staged query.
func (b {{$model.Name}}QueryBuilder) Where(clauses ...query.{{$model.Name}}WhereClause) {{$model.Name}}QueryBuilder {
	opts := make([]query.{{$model.Name}}QueryOption, len(clauses))
	for i, clause := range clauses {
		opts[i] = clause
	}
	return b.withOptions(opts...)
}

// OrderBy appends an ORDER BY clause to the staged query.
func (b {{$model.Name}}QueryBuilder) OrderBy(clause query.{{$model.Name}}OrderByClause) {{$model.Name}}QueryBuilder {
	return b.withOptions(clause)
}

// Include appends include clauses to the staged query.
func (b {{$model.Name}}QueryBuilder) Include(clauses ...query.{{$model.Name}}IncludeClause) {{$model.Name}}QueryBuilder {
	opts := make([]query.{{$model.Name}}QueryOption, len(clauses))
	for i, clause := range clauses {
		opts[i] = clause
	}
	return b.withOptions(opts...)
}

// Take applies a LIMIT to the staged query.
func (b {{$model.Name}}QueryBuilder) Take(n int) {{$model.Name}}QueryBuilder {
	return b.withOptions(query.{{$model.Name}}TakeOption{N: n})
}

// Skip applies an OFFSET to the staged query.
func (b {{$model.Name}}QueryBuilder) Skip(n int) {{$model.Name}}QueryBuilder {
	return b.withOptions(query.{{$model.Name}}SkipOption{N: n})
}

// Do executes the staged query and returns all matching rows.
func (b {{$model.Name}}QueryBuilder) Do(ctx context.Context) ([]model.{{$model.Name}}, error) {
	return b.action.FindMany(ctx, b.opts...)
}

// First executes the staged query and returns the first matching row.
func (b {{$model.Name}}QueryBuilder) First(ctx context.Context) (*model.{{$model.Name}}, error) {
	return b.action.FindFirst(ctx, b.opts...)
}

// Count executes the staged query as a COUNT over its WHERE clauses.
func (b {{$model.Name}}QueryBuilder) Count(ctx context.Context) (int64, error) {
	cfg := query.Apply{{$model.Name}}Options(b.opts)
	return b.action.Count(ctx, cfg.Wheres...)
}

// {{$model.Name}}UpdateBuilder builds a {{$model.Name}} update operation incrementally.
type {{$model.Name}}UpdateBuilder struct {
	action {{$model.Name}}Actions
	wheres []query.{{$model.Name}}WhereClause
	sets   []query.{{$model.Name}}SetClause
}

// Update starts a staged {{$model.Name}} update operation.
func (a {{$model.Name}}Actions) Update() {{$model.Name}}UpdateBuilder {
	return {{$model.Name}}UpdateBuilder{action: a}
}

// Where appends WHERE clauses to the staged update operation.
func (b {{$model.Name}}UpdateBuilder) Where(clauses ...query.{{$model.Name}}WhereClause) {{$model.Name}}UpdateBuilder {
	next := {{$model.Name}}UpdateBuilder{
		action: b.action,
		wheres: make([]query.{{$model.Name}}WhereClause, 0, len(b.wheres)+len(clauses)),
		sets:   append([]query.{{$model.Name}}SetClause(nil), b.sets...),
	}
	next.wheres = append(next.wheres, b.wheres...)
	next.wheres = append(next.wheres, clauses...)
	return next
}

// Set appends field assignments to the staged update operation.
func (b {{$model.Name}}UpdateBuilder) Set(sets ...query.{{$model.Name}}SetClause) {{$model.Name}}UpdateBuilder {
	next := {{$model.Name}}UpdateBuilder{
		action: b.action,
		wheres: append([]query.{{$model.Name}}WhereClause(nil), b.wheres...),
		sets:   make([]query.{{$model.Name}}SetClause, 0, len(b.sets)+len(sets)),
	}
	next.sets = append(next.sets, b.sets...)
	next.sets = append(next.sets, sets...)
	return next
}

func (b {{$model.Name}}UpdateBuilder) combinedWhere() (query.{{$model.Name}}WhereClause, error) {
	if len(b.wheres) == 0 {
		return query.{{$model.Name}}WhereClause{}, fmt.Errorf("{{$model.Name}}.Update.Do: no where clause provided")
	}
	if len(b.wheres) == 1 {
		return b.wheres[0], nil
	}
	return query.{{$model.Name}}.AND(b.wheres...), nil
}

// Do executes the staged update as a single-row update.
func (b {{$model.Name}}UpdateBuilder) Do(ctx context.Context) (*model.{{$model.Name}}, error) {
	where, err := b.combinedWhere()
	if err != nil {
		return nil, err
	}
	return b.action.UpdateOne(ctx, where, b.sets...)
}

// DoMany executes the staged update as a multi-row update.
func (b {{$model.Name}}UpdateBuilder) DoMany(ctx context.Context) (int64, error) {
	return b.action.UpdateMany(ctx, b.wheres, b.sets...)
}

// {{$model.Name}}DeleteBuilder builds a {{$model.Name}} delete operation incrementally.
type {{$model.Name}}DeleteBuilder struct {
	action {{$model.Name}}Actions
	wheres []query.{{$model.Name}}WhereClause
}

// Delete starts a staged {{$model.Name}} delete operation.
func (a {{$model.Name}}Actions) Delete() {{$model.Name}}DeleteBuilder {
	return {{$model.Name}}DeleteBuilder{action: a}
}

// Where appends WHERE clauses to the staged delete operation.
func (b {{$model.Name}}DeleteBuilder) Where(clauses ...query.{{$model.Name}}WhereClause) {{$model.Name}}DeleteBuilder {
	next := {{$model.Name}}DeleteBuilder{
		action: b.action,
		wheres: make([]query.{{$model.Name}}WhereClause, 0, len(b.wheres)+len(clauses)),
	}
	next.wheres = append(next.wheres, b.wheres...)
	next.wheres = append(next.wheres, clauses...)
	return next
}

func (b {{$model.Name}}DeleteBuilder) combinedWhere() (query.{{$model.Name}}WhereClause, error) {
	if len(b.wheres) == 0 {
		return query.{{$model.Name}}WhereClause{}, fmt.Errorf("{{$model.Name}}.Delete.Do: no where clause provided")
	}
	if len(b.wheres) == 1 {
		return b.wheres[0], nil
	}
	return query.{{$model.Name}}.AND(b.wheres...), nil
}

// Do executes the staged delete as a single-row delete.
func (b {{$model.Name}}DeleteBuilder) Do(ctx context.Context) (*model.{{$model.Name}}, error) {
	where, err := b.combinedWhere()
	if err != nil {
		return nil, err
	}
	return b.action.DeleteOne(ctx, where)
}

// DoMany executes the staged delete as a multi-row delete.
func (b {{$model.Name}}DeleteBuilder) DoMany(ctx context.Context) (int64, error) {
	return b.action.DeleteMany(ctx, b.wheres...)
}

// FindMany retrieves multiple {{$model.Name}} records.
func (a {{$model.Name}}Actions) FindMany(ctx context.Context, opts ...query.{{$model.Name}}QueryOption) ([]model.{{$model.Name}}, error) {
	cfg := query.Apply{{$model.Name}}Options(opts)
	q := "SELECT {{columnCSV $model}} FROM {{tableName $model}}"
	argIdx := 0
	where, args := build{{$model.Name}}Where(a.client, cfg.Wheres, &argIdx)
	if where != "" {
		q += " WHERE " + where
	}
	if len(cfg.OrderBys) > 0 {
		obs := make([]string, len(cfg.OrderBys))
		for i, ob := range cfg.OrderBys {
			obs[i] = ob.Field + " " + ob.Direction
		}
		q += " ORDER BY " + strings.Join(obs, ", ")
	}
	if cfg.Take != nil {
		q += fmt.Sprintf(" LIMIT %d", *cfg.Take)
	}
	if cfg.Skip != nil {
		q += fmt.Sprintf(" OFFSET %d", *cfg.Skip)
	}
	rows, err := a.client.executor.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("{{$model.Name}}.FindMany: %w", err)
	}
	defer rows.Close()
	var results []model.{{$model.Name}}
	for rows.Next() {
		var item model.{{$model.Name}}
		if err := rows.Scan({{scanFields $model}}); err != nil {
			return nil, fmt.Errorf("{{$model.Name}}.FindMany scan: %w", err)
		}
		results = append(results, item)
	}
	return results, rows.Err()
}

// FindFirst retrieves the first matching {{$model.Name}} record.
func (a {{$model.Name}}Actions) FindFirst(ctx context.Context, opts ...query.{{$model.Name}}QueryOption) (*model.{{$model.Name}}, error) {
	opts = append(opts, query.{{$model.Name}}TakeOption{N: 1})
	results, err := a.FindMany(ctx, opts...)
	if err != nil {
		return nil, err
	}
	if len(results) == 0 {
		return nil, nil
	}
	return &results[0], nil
}

// FindUnique retrieves a single {{$model.Name}} record by unique constraint.
func (a {{$model.Name}}Actions) FindUnique(ctx context.Context, where query.{{$model.Name}}WhereClause) (*model.{{$model.Name}}, error) {
	argIdx := 0
	whereSQL, args := build{{$model.Name}}Where(a.client, []query.{{$model.Name}}WhereClause{where}, &argIdx)
	q := "SELECT {{columnCSV $model}} FROM {{tableName $model}}"
	if whereSQL != "" {
		q += " WHERE " + whereSQL
	}
	q += " LIMIT 1"
	row := a.client.executor.QueryRowContext(ctx, q, args...)
	var item model.{{$model.Name}}
	if err := row.Scan({{scanFields $model}}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, fmt.Errorf("{{$model.Name}}.FindUnique: %w", err)
	}
	return &item, nil
}

// CreateOne creates a single {{$model.Name}} record.
func (a {{$model.Name}}Actions) CreateOne(ctx context.Context, sets ...query.{{$model.Name}}SetClause) (*model.{{$model.Name}}, error) {
	if len(sets) == 0 {
		return nil, fmt.Errorf("{{$model.Name}}.CreateOne: no fields provided")
	}
	cols := make([]string, len(sets))
	vals := make([]any, len(sets))
	phs := make([]string, len(sets))
	for i, s := range sets {
		cols[i] = s.Field
		vals[i] = s.Value
		phs[i] = a.client.placeholder(i + 1)
	}
	q := fmt.Sprintf("INSERT INTO {{tableName $model}} (%s) VALUES (%s)",
		strings.Join(cols, ", "), strings.Join(phs, ", "))
	if a.client.dialect == "postgresql" {
		q += " RETURNING {{columnCSV $model}}"
		row := a.client.executor.QueryRowContext(ctx, q, vals...)
		var item model.{{$model.Name}}
		if err := row.Scan({{scanFields $model}}); err != nil {
			return nil, fmt.Errorf("{{$model.Name}}.CreateOne: %w", err)
		}
		return &item, nil
	}
	result, err := a.client.executor.ExecContext(ctx, q, vals...)
	if err != nil {
		return nil, fmt.Errorf("{{$model.Name}}.CreateOne: %w", err)
	}
	_ = result
	return nil, nil
}

// CreateMany creates multiple {{$model.Name}} records.
func (a {{$model.Name}}Actions) CreateMany(ctx context.Context, data []query.{{$model.Name}}CreateInput) (int64, error) {
	return a.BulkCreate(data).Do(ctx)
}

func (a {{$model.Name}}Actions) build{{$model.Name}}CreateManySQL(data []query.{{$model.Name}}CreateInput, conflictDoNothing bool, conflictColumns []string, returningColumns []string) (string, []any) {
	cols := []string{ {{scalarColNamesCSV $model}} }
	argIdx := 0
	var valueSets []string
	var args []any
	for _, d := range data {
		row := d.ScalarValues()
		phs := make([]string, len(row))
		for i, v := range row {
			argIdx++
			phs[i] = a.client.placeholder(argIdx)
			args = append(args, v)
		}
		valueSets = append(valueSets, "("+strings.Join(phs, ", ")+")")
	}
	q := fmt.Sprintf("INSERT INTO {{tableName $model}} (%s) VALUES %s",
		strings.Join(cols, ", "), strings.Join(valueSets, ", "))
	if conflictDoNothing {
		switch a.client.dialect {
		case "mysql":
			if len(cols) > 0 {
				q += " ON DUPLICATE KEY UPDATE " + cols[0] + " = " + cols[0]
			}
		default:
			q += " ON CONFLICT"
			if len(conflictColumns) > 0 {
				q += " (" + strings.Join(conflictColumns, ", ") + ")"
			}
			q += " DO NOTHING"
		}
	}
	if len(returningColumns) > 0 {
		q += " RETURNING " + strings.Join(returningColumns, ", ")
	}
	return q, args
}

// UpdateOne updates a single {{$model.Name}} record matching the where clause.
func (a {{$model.Name}}Actions) UpdateOne(ctx context.Context, where query.{{$model.Name}}WhereClause, sets ...query.{{$model.Name}}SetClause) (*model.{{$model.Name}}, error) {
	if len(sets) == 0 {
		return nil, fmt.Errorf("{{$model.Name}}.UpdateOne: no fields to update")
	}
	argIdx := 0
	setParts := make([]string, len(sets))
	args := make([]any, 0, len(sets)+1)
	for i, s := range sets {
		argIdx++
		setParts[i] = s.Field + " = " + a.client.placeholder(argIdx)
		args = append(args, s.Value)
	}
	whereSQL, whereArgs := build{{$model.Name}}Where(a.client, []query.{{$model.Name}}WhereClause{where}, &argIdx)
	args = append(args, whereArgs...)
	q := fmt.Sprintf("UPDATE {{tableName $model}} SET %s", strings.Join(setParts, ", "))
	if whereSQL != "" {
		q += " WHERE " + whereSQL
	}
	if a.client.dialect == "postgresql" {
		q += " RETURNING {{columnCSV $model}}"
		row := a.client.executor.QueryRowContext(ctx, q, args...)
		var item model.{{$model.Name}}
		if err := row.Scan({{scanFields $model}}); err != nil {
			if err == sql.ErrNoRows {
				return nil, nil
			}
			return nil, fmt.Errorf("{{$model.Name}}.UpdateOne: %w", err)
		}
		return &item, nil
	}
	_, err := a.client.executor.ExecContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("{{$model.Name}}.UpdateOne: %w", err)
	}
	return nil, nil
}

// UpdateMany updates multiple {{$model.Name}} records matching the where clauses.
func (a {{$model.Name}}Actions) UpdateMany(ctx context.Context, wheres []query.{{$model.Name}}WhereClause, sets ...query.{{$model.Name}}SetClause) (int64, error) {
	if len(sets) == 0 {
		return 0, fmt.Errorf("{{$model.Name}}.UpdateMany: no fields to update")
	}
	argIdx := 0
	setParts := make([]string, len(sets))
	args := make([]any, 0, len(sets)+len(wheres))
	for i, s := range sets {
		argIdx++
		setParts[i] = s.Field + " = " + a.client.placeholder(argIdx)
		args = append(args, s.Value)
	}
	whereSQL, whereArgs := build{{$model.Name}}Where(a.client, wheres, &argIdx)
	args = append(args, whereArgs...)
	q := fmt.Sprintf("UPDATE {{tableName $model}} SET %s", strings.Join(setParts, ", "))
	if whereSQL != "" {
		q += " WHERE " + whereSQL
	}
	result, err := a.client.executor.ExecContext(ctx, q, args...)
	if err != nil {
		return 0, fmt.Errorf("{{$model.Name}}.UpdateMany: %w", err)
	}
	return result.RowsAffected()
}

// UpsertOne creates or updates a single {{$model.Name}} record.
func (a {{$model.Name}}Actions) UpsertOne(ctx context.Context, where query.{{$model.Name}}WhereClause, create []query.{{$model.Name}}SetClause, update []query.{{$model.Name}}SetClause) (*model.{{$model.Name}}, error) {
	if len(create) == 0 {
		return nil, fmt.Errorf("{{$model.Name}}.UpsertOne: no create fields provided")
	}
	argIdx := 0
	cols := make([]string, len(create))
	phs := make([]string, len(create))
	args := make([]any, 0, len(create)+len(update))
	for i, s := range create {
		cols[i] = s.Field
		argIdx++
		phs[i] = a.client.placeholder(argIdx)
		args = append(args, s.Value)
	}
	q := fmt.Sprintf("INSERT INTO {{tableName $model}} (%s) VALUES (%s)",
		strings.Join(cols, ", "), strings.Join(phs, ", "))
	if a.client.dialect == "mysql" {
		if len(update) > 0 {
			uParts := make([]string, len(update))
			for i, s := range update {
				argIdx++
				uParts[i] = s.Field + " = " + a.client.placeholder(argIdx)
				args = append(args, s.Value)
			}
			q += " ON DUPLICATE KEY UPDATE " + strings.Join(uParts, ", ")
		}
	} else {
		q += fmt.Sprintf(" ON CONFLICT (%s) DO", where.Field)
		if len(update) > 0 {
			uParts := make([]string, len(update))
			for i, s := range update {
				argIdx++
				uParts[i] = s.Field + " = " + a.client.placeholder(argIdx)
				args = append(args, s.Value)
			}
			q += " UPDATE SET " + strings.Join(uParts, ", ")
		} else {
			q += " NOTHING"
		}
	}
	if a.client.dialect == "postgresql" {
		q += " RETURNING {{columnCSV $model}}"
		row := a.client.executor.QueryRowContext(ctx, q, args...)
		var item model.{{$model.Name}}
		if err := row.Scan({{scanFields $model}}); err != nil {
			return nil, fmt.Errorf("{{$model.Name}}.UpsertOne: %w", err)
		}
		return &item, nil
	}
	_, err := a.client.executor.ExecContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("{{$model.Name}}.UpsertOne: %w", err)
	}
	return nil, nil
}

// DeleteOne deletes a single {{$model.Name}} record matching the where clause.
func (a {{$model.Name}}Actions) DeleteOne(ctx context.Context, where query.{{$model.Name}}WhereClause) (*model.{{$model.Name}}, error) {
	argIdx := 0
	whereSQL, args := build{{$model.Name}}Where(a.client, []query.{{$model.Name}}WhereClause{where}, &argIdx)
	q := "DELETE FROM {{tableName $model}}"
	if whereSQL != "" {
		q += " WHERE " + whereSQL
	}
	if a.client.dialect == "postgresql" {
		q += " RETURNING {{columnCSV $model}}"
		row := a.client.executor.QueryRowContext(ctx, q, args...)
		var item model.{{$model.Name}}
		if err := row.Scan({{scanFields $model}}); err != nil {
			if err == sql.ErrNoRows {
				return nil, nil
			}
			return nil, fmt.Errorf("{{$model.Name}}.DeleteOne: %w", err)
		}
		return &item, nil
	}
	_, err := a.client.executor.ExecContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("{{$model.Name}}.DeleteOne: %w", err)
	}
	return nil, nil
}

// DeleteMany deletes multiple {{$model.Name}} records matching the where clauses.
func (a {{$model.Name}}Actions) DeleteMany(ctx context.Context, wheres ...query.{{$model.Name}}WhereClause) (int64, error) {
	argIdx := 0
	whereSQL, args := build{{$model.Name}}Where(a.client, wheres, &argIdx)
	q := "DELETE FROM {{tableName $model}}"
	if whereSQL != "" {
		q += " WHERE " + whereSQL
	}
	result, err := a.client.executor.ExecContext(ctx, q, args...)
	if err != nil {
		return 0, fmt.Errorf("{{$model.Name}}.DeleteMany: %w", err)
	}
	return result.RowsAffected()
}

// Count returns the number of {{$model.Name}} records matching the where clauses.
func (a {{$model.Name}}Actions) Count(ctx context.Context, wheres ...query.{{$model.Name}}WhereClause) (int64, error) {
	argIdx := 0
	whereSQL, args := build{{$model.Name}}Where(a.client, wheres, &argIdx)
	q := "SELECT COUNT(*) FROM {{tableName $model}}"
	if whereSQL != "" {
		q += " WHERE " + whereSQL
	}
	var count int64
	if err := a.client.executor.QueryRowContext(ctx, q, args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("{{$model.Name}}.Count: %w", err)
	}
	return count, nil
}

// Aggregate computes aggregate values for {{$model.Name}}.
func (a {{$model.Name}}Actions) Aggregate(ctx context.Context, opts ...query.{{$model.Name}}AggregateOption) (*query.{{$model.Name}}AggregateResult, error) {
	selParts := []string{"COUNT(*)"}
	for _, opt := range opts {
		selParts = append(selParts, fmt.Sprintf("%s(%s)", strings.ToUpper(opt.Fn), opt.Field))
	}
	q := fmt.Sprintf("SELECT %s FROM {{tableName $model}}", strings.Join(selParts, ", "))
	row := a.client.executor.QueryRowContext(ctx, q)
	result := &query.{{$model.Name}}AggregateResult{
		Avg: make(map[string]*float64),
		Sum: make(map[string]*float64),
		Min: make(map[string]any),
		Max: make(map[string]any),
	}
	aggVals := make([]sql.NullFloat64, len(opts))
	scanDest := make([]any, 0, 1+len(opts))
	scanDest = append(scanDest, &result.Count)
	for i := range opts {
		scanDest = append(scanDest, &aggVals[i])
	}
	if err := row.Scan(scanDest...); err != nil {
		return nil, fmt.Errorf("{{$model.Name}}.Aggregate: %w", err)
	}
	for i, opt := range opts {
		if aggVals[i].Valid {
			v := aggVals[i].Float64
			switch opt.Fn {
			case "avg":
				result.Avg[opt.Field] = &v
			case "sum":
				result.Sum[opt.Field] = &v
			case "min":
				result.Min[opt.Field] = v
			case "max":
				result.Max[opt.Field] = v
			}
		}
	}
	return result, nil
}

// GroupBy performs a GROUP BY query on {{$model.Name}}.
func (a {{$model.Name}}Actions) GroupBy(ctx context.Context, fields []string, opts ...query.{{$model.Name}}AggregateOption) ([]query.{{$model.Name}}GroupByResult, error) {
	selParts := make([]string, 0, len(fields)+1+len(opts))
	selParts = append(selParts, fields...)
	selParts = append(selParts, "COUNT(*)")
	for _, opt := range opts {
		selParts = append(selParts, fmt.Sprintf("%s(%s)", strings.ToUpper(opt.Fn), opt.Field))
	}
	q := fmt.Sprintf("SELECT %s FROM {{tableName $model}} GROUP BY %s",
		strings.Join(selParts, ", "), strings.Join(fields, ", "))
	rows, err := a.client.executor.QueryContext(ctx, q)
	if err != nil {
		return nil, fmt.Errorf("{{$model.Name}}.GroupBy: %w", err)
	}
	defer rows.Close()
	var results []query.{{$model.Name}}GroupByResult
	for rows.Next() {
		r := query.{{$model.Name}}GroupByResult{
			Group: make(map[string]any),
			Avg:   make(map[string]*float64),
			Sum:   make(map[string]*float64),
			Min:   make(map[string]any),
			Max:   make(map[string]any),
		}
		groupVals := make([]any, len(fields))
		scanDest := make([]any, 0, len(fields)+1+len(opts))
		for i := range fields {
			groupVals[i] = new(any)
			scanDest = append(scanDest, groupVals[i])
		}
		scanDest = append(scanDest, &r.Count)
		aggVals := make([]sql.NullFloat64, len(opts))
		for i := range opts {
			scanDest = append(scanDest, &aggVals[i])
		}
		if err := rows.Scan(scanDest...); err != nil {
			return nil, fmt.Errorf("{{$model.Name}}.GroupBy scan: %w", err)
		}
		for i, f := range fields {
			r.Group[f] = *(groupVals[i].(*any))
		}
		for i, opt := range opts {
			if aggVals[i].Valid {
				v := aggVals[i].Float64
				switch opt.Fn {
				case "avg":
					r.Avg[opt.Field] = &v
				case "sum":
					r.Sum[opt.Field] = &v
				case "min":
					r.Min[opt.Field] = v
				case "max":
					r.Max[opt.Field] = v
				}
			}
		}
		results = append(results, r)
	}
	return results, rows.Err()
}
{{end}}
`
