package dialect

import (
	"database/sql"
	stderrors "errors"
	"fmt"
	"strings"

	"github.com/arsfy/gco-orm/pkg/runtime"
	gcoerr "github.com/arsfy/gco-orm/pkg/runtime/errors"
)

// PostgreSQL implements the runtime.Dialect interface for PostgreSQL databases.
type PostgreSQL struct{}

func (PostgreSQL) Name() string { return "postgresql" }

func (PostgreSQL) Placeholder(n int) string { return fmt.Sprintf("$%d", n) }

func (PostgreSQL) QuoteIdent(parts ...string) string {
	quoted := make([]string, len(parts))
	for i, p := range parts {
		quoted[i] = `"` + p + `"`
	}
	return strings.Join(quoted, ".")
}

func (PostgreSQL) SupportsReturning() bool { return true }

func (PostgreSQL) SupportsSchemas() bool { return true }

func (PostgreSQL) RewriteLimitOffset(limit, offset *int) string {
	var sb strings.Builder
	if limit != nil {
		sb.WriteString(fmt.Sprintf("LIMIT %d", *limit))
	}
	if offset != nil {
		if sb.Len() > 0 {
			sb.WriteByte(' ')
		}
		sb.WriteString(fmt.Sprintf("OFFSET %d", *offset))
	}
	return sb.String()
}

func (PostgreSQL) ClassifyError(err error) *runtime.DBError {
	if err == nil {
		return nil
	}

	if stderrors.Is(err, sql.ErrNoRows) {
		return gcoerr.Wrap(err, gcoerr.CodeNotFound, "record not found")
	}

	msg := err.Error()

	switch {
	case containsAny(msg, "unique_violation", "23505", "duplicate key"):
		e := gcoerr.Wrap(err, gcoerr.CodeUniqueViolation, "unique constraint violated")
		if c := extractBetweenQuotes(msg, "constraint"); c != "" {
			e = e.WithMeta("constraint", c)
		}
		return e

	case containsAny(msg, "foreign_key_violation", "23503", "foreign key constraint"):
		e := gcoerr.Wrap(err, gcoerr.CodeForeignKeyViolation, "foreign key constraint violated")
		if c := extractBetweenQuotes(msg, "constraint"); c != "" {
			e = e.WithMeta("constraint", c)
		}
		return e

	case containsAny(msg, "not_null_violation", "23502", "null value in column"):
		return gcoerr.Wrap(err, gcoerr.CodeNotNullViolation, "not-null constraint violated")

	case containsAny(msg, "check_violation", "23514"):
		return gcoerr.Wrap(err, gcoerr.CodeCheckViolation, "check constraint violated")

	case containsAny(msg, "40001", "serialization_failure"):
		return gcoerr.Wrap(err, gcoerr.CodeSerializationFailure, "serialization failure")

	case containsAny(msg, "40p01", "deadlock detected"):
		return gcoerr.Wrap(err, gcoerr.CodeDeadlock, "deadlock detected")

	case containsAny(msg, "57014", "canceling statement", "statement timeout"):
		return gcoerr.Wrap(err, gcoerr.CodeTimeout, "query timeout")

	case containsAny(msg, "22001"):
		return gcoerr.Wrap(err, gcoerr.CodeDataTruncation, "data truncation")

	case containsAny(msg, "08000", "08001", "08003", "08004", "08006",
		"connection refused", "connection reset", "broken pipe"):
		return gcoerr.Wrap(err, gcoerr.CodeConnectionError, "connection error")
	}

	return nil
}

func (PostgreSQL) TypeMapping(schemaType string, isOptional bool) string {
	var t string
	switch schemaType {
	case "String":
		t = "TEXT"
	case "Int":
		t = "INTEGER"
	case "BigInt":
		t = "BIGINT"
	case "Float":
		t = "DOUBLE PRECISION"
	case "Decimal":
		t = "DECIMAL"
	case "Boolean":
		t = "BOOLEAN"
	case "DateTime":
		t = "TIMESTAMPTZ"
	case "Bytes":
		t = "BYTEA"
	case "Json":
		t = "JSONB"
	case "UUID":
		t = "UUID"
	default:
		t = "TEXT"
	}
	return t
}

func (PostgreSQL) DefaultValueExpression(funcName string, args []string) string {
	switch funcName {
	case "uuid":
		return "gen_random_uuid()"
	case "now":
		return "NOW()"
	case "autoincrement":
		return "GENERATED BY DEFAULT AS IDENTITY"
	case "sequence":
		if len(args) > 0 {
			return fmt.Sprintf("nextval('%s')", args[0])
		}
		return "nextval('unnamed_seq')"
	default:
		return funcName + "()"
	}
}

func (PostgreSQL) SupportsFeature(feature runtime.Feature) bool {
	switch feature {
	case runtime.FeatureReturning,
		runtime.FeatureSchemas,
		runtime.FeatureJSON,
		runtime.FeatureUUID,
		runtime.FeatureArrays,
		runtime.FeatureEnumType,
		runtime.FeatureCascadeDelete,
		runtime.FeatureIdentityColumn,
		runtime.FeatureUpsert,
		runtime.FeaturePartialIndex:
		return true
	case runtime.FeatureSerialType:
		return true
	default:
		return false
	}
}

// Compile-time check.
var _ runtime.Dialect = PostgreSQL{}
